export const STUDY_WORD_LISTS: { id: string; name: string; isStudy: boolean; words: string[] }[] = [
  {
    id: 'us-geography',
    name: 'US Geography',
    isStudy: true,
    words: [
      'Alabama',
      'Montgomery',
      'Alaska',
      'Juneau',
      'Arizona',
      'Phoenix',
      'Arkansas',
      'Little Rock',
      'California',
      'Sacramento',
      'Colorado',
      'Denver',
      'Connecticut',
      'Hartford',
      'Delaware',
      'Dover',
      'Florida',
      'Tallahassee',
      'Georgia',
      'Atlanta',
      'Hawaii',
      'Honolulu',
      'Idaho',
      'Boise',
      'Illinois',
      'Springfield',
      'Indiana',
      'Indianapolis',
      'Iowa',
      'Des Moines',
      'Kansas',
      'Topeka',
      'Kentucky',
      'Frankfort',
      'Louisiana',
      'Baton Rouge',
      'Maine',
      'Augusta',
      'Maryland',
      'Annapolis',
      'Massachusetts',
      'Boston',
      'Michigan',
      'Lansing',
      'Minnesota',
      'Saint Paul',
      'Mississippi',
      'Jackson',
      'Missouri',
      'Jefferson City',
      'Montana',
      'Helena',
      'Nebraska',
      'Lincoln',
      'Nevada',
      'Carson City',
      'New Hampshire',
      'Concord',
      'New Jersey',
      'Trenton',
      'New Mexico',
      'Santa Fe',
      'New York',
      'Albany',
      'North Carolina',
      'Raleigh',
      'North Dakota',
      'Bismarck',
      'Ohio',
      'Columbus',
      'Oklahoma',
      'Oklahoma City',
      'Oregon',
      'Salem',
      'Pennsylvania',
      'Harrisburg',
      'Rhode Island',
      'Providence',
      'South Carolina',
      'Columbia',
      'South Dakota',
      'Pierre',
      'Tennessee',
      'Nashville',
      'Texas',
      'Austin',
      'Utah',
      'Salt Lake City',
      'Vermont',
      'Montpelier',
      'Virginia',
      'Richmond',
      'Washington',
      'Olympia',
      'West Virginia',
      'Charleston',
      'Wisconsin',
      'Madison',
      'Wyoming',
      'Cheyenne',
      'New York City',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Miami',
      'San Francisco',
      'Seattle',
      'Las Vegas',
      'San Diego',
      'Dallas',
      'San Antonio',
      'Philadelphia',
      'Detroit',
      'Portland',
      'Minneapolis',
      'New Orleans',
      'Baltimore',
      'Milwaukee',
      'Cleveland',
      'Pittsburgh',
      'Cincinnati',
      'Kansas City',
      'Tampa',
      'Orlando',
      'Charlotte',
      'Statue of Liberty',
      'Golden Gate Bridge',
      'Mount Rushmore',
      'Hollywood Sign',
      'Empire State Building',
      'White House',
      'Lincoln Memorial',
      'Washington Monument',
      'Space Needle',
      'Gateway Arch',
      'Brooklyn Bridge',
      'Hoover Dam',
      'Freedom Trail',
      'Alcatraz Island',
      'Pearl Harbor',
      'Independence Hall',
      'Liberty Bell',
      'Niagara Falls',
      'Times Square',
      'Central Park',
      'Grand Central Station',
      'Las Vegas Strip',
      'Navy Pier',
      'Fisherman\'s Wharf',
      'French Quarter',
      'Grand Canyon',
      'Yellowstone',
      'Yosemite',
      'Zion',
      'Glacier Nat\'l Park',
      'Rocky Mountain',
      'Great Smoky Mountains',
      'Acadia',
      'Olympic Nat\'l Park',
      'Joshua Tree',
      'Death Valley',
      'Everglades',
      'Bryce Canyon',
      'Arches',
      'Sequoia',
      'Redwood',
      'Denali',
      'Hawaii Volcanoes',
      'Crater Lake',
      'Mesa Verde',
      'Badlands',
      'Shenandoah',
      'Big Bend',
      'Canyonlands',
      'Capitol Reef',
      'Mississippi River',
      'Colorado River',
      'Missouri River',
      'Great Lakes',
      'Lake Michigan',
      'Lake Superior',
      'Lake Erie',
      'Lake Tahoe',
      'Chesapeake Bay',
      'Puget Sound',
      'Florida Keys',
      'Cape Cod',
      'Martha\'s Vineyard',
      'Long Island',
      'Manhattan',
      'Hollywood',
      'Silicon Valley',
      'Wall Street',
      'Broadway',
      'Bourbon Street',
      'Route 66',
      'Pacific Coast Highway',
      'Appalachian Trail',
      'Mount Whitney',
      'Mount Rainier'
    ]
  },
  {
    id: 'world-geography',
    name: 'World Geography',
    isStudy: true,
    words: [
      'Canada',
      'Ottawa',
      'Mexico',
      'Mexico City',
      'Brazil',
      'Brasilia',
      'Argentina',
      'Buenos Aires',
      'Chile',
      'Santiago',
      'Peru',
      'Lima',
      'Colombia',
      'Bogota',
      'Venezuela',
      'Caracas',
      'Ecuador',
      'Quito',
      'United Kingdom',
      'London',
      'France',
      'Paris',
      'Germany',
      'Berlin',
      'Italy',
      'Rome',
      'Spain',
      'Madrid',
      'Portugal',
      'Lisbon',
      'Netherlands',
      'Amsterdam',
      'Belgium',
      'Brussels',
      'Switzerland',
      'Bern',
      'Austria',
      'Vienna',
      'Poland',
      'Warsaw',
      'Greece',
      'Athens',
      'Sweden',
      'Stockholm',
      'Norway',
      'Oslo',
      'Denmark',
      'Copenhagen',
      'Finland',
      'Helsinki',
      'Ireland',
      'Dublin',
      'Scotland',
      'Edinburgh',
      'Russia',
      'Moscow',
      'Ukraine',
      'Kyiv',
      'Turkey',
      'Ankara',
      'China',
      'Beijing',
      'Japan',
      'Tokyo',
      'South Korea',
      'Seoul',
      'India',
      'New Delhi',
      'Thailand',
      'Bangkok',
      'Vietnam',
      'Hanoi',
      'Indonesia',
      'Jakarta',
      'Philippines',
      'Manila',
      'Malaysia',
      'Kuala Lumpur',
      'Singapore',
      'Australia',
      'Canberra',
      'New Zealand',
      'Wellington',
      'Egypt',
      'Cairo',
      'South Africa',
      'Pretoria',
      'Morocco',
      'Rabat',
      'Kenya',
      'Nairobi',
      'Nigeria',
      'Abuja',
      'Ethiopia',
      'Addis Ababa',
      'Israel',
      'Jerusalem',
      'Saudi Arabia',
      'Riyadh',
      'United Arab Emirates',
      'Abu Dhabi',
      'Toronto',
      'Vancouver',
      'Montreal',
      'Sydney',
      'Melbourne',
      'Auckland',
      'Rio de Janeiro',
      'Sao Paulo',
      'Barcelona',
      'Milan',
      'Munich',
      'Prague',
      'Budapest',
      'Venice',
      'Florence',
      'Nice',
      'Geneva',
      'Zurich',
      'Hong Kong',
      'Shanghai',
      'Dubai',
      'Mumbai',
      'Bangalore',
      'Cape Town',
      'Marrakech',
      'Istanbul',
      'St. Petersburg',
      'Kyoto',
      'Osaka',
      'Atlantic Ocean',
      'Pacific Ocean',
      'Indian Ocean',
      'Arctic Ocean',
      'Southern Ocean',
      'Mediterranean Sea',
      'Caribbean Sea',
      'Red Sea',
      'Black Sea',
      'Baltic Sea',
      'North Sea',
      'South China Sea',
      'Bay of Bengal',
      'Persian Gulf',
      'Gulf of Mexico',
      'Amazon River',
      'Nile River',
      'Ganges River',
      'Yangtze River',
      'Danube River',
      'Thames River',
      'Seine River',
      'Rhine River',
      'Volga River',
      'Congo River',
      'Dead Sea',
      'Caspian Sea',
      'Lake Victoria',
      'Lake Baikal',
      'Great Barrier Reef',
      'Eiffel Tower',
      'Big Ben',
      'Colosseum',
      'Leaning Tower of Pisa',
      'Stonehenge',
      'Taj Mahal',
      'Great Wall of China',
      'Machu Picchu',
      'Christ the Redeemer',
      'Petra',
      'Pyramids of Giza',
      'Sphinx',
      'Acropolis',
      'Parthenon',
      'Tower of London',
      'Buckingham Palace',
      'Vatican City',
      'Sistine Chapel',
      'Notre Dame',
      'Louvre',
      'Sydney Opera House',
      'Burj Khalifa',
      'Mount Everest',
      'Mount Fuji',
      'Matterhorn',
      'Amazon Rainforest',
      'Sahara Desert',
      'Gobi Desert',
      'Himalayas',
      'Alps',
      'Andes Mountains',
      'Victoria Falls',
      'Angel Falls',
      'Iguazu Falls',
      'Northern Lights',
      'Santorini',
      'Bali',
      'Fiji',
      'Maldives',
      'Galapagos Islands'
    ]
  },
  {
    id: 'mandarin',
    name: 'Mandarin',
    isStudy: true,
    words: [
      '爱 (ài)',
      '不好 (bù hǎo)',
      '不是 (búshì)',
      '不 (bù)',
      '不可以 (bùxíng)',
      '吃 (chī)',
      '茶 (chá)',
      '唱 (chàng)',
      '车 (chē)',
      '大 (dà)',
      '打开 (dǎkāi)',
      '读 (dú)',
      '对不起 (duìbùqǐ)',
      '放 (fàng)',
      '给 (gěi)',
      '高兴 (gāoxìng)',
      '歌 (gē)',
      '狗 (gǒu)',
      '关上 (guānshàng)',
      '很 (hěn)',
      '好 (hǎo)',
      '喝 (hē)',
      '医院 (yīyuàn)',
      '会 (huì)',
      '画 (huà)',
      '家 (jiā)',
      '今天 (jīntiān)',
      '跳 (tiào)',
      '跳舞 (tiàowǔ)',
      '咖啡 (kāfēi)',
      '看 (kàn)',
      '来 (lái)',
      '冷 (lěng)',
      '老师 (lǎoshī)',
      '妈妈 (māma)',
      '猫 (māo)',
      '买 (mǎi)',
      '没有 (méiyǒu)',
      '明天 (míngtiān)',
      '名字 (míngzi)',
      '米饭 (mǐfàn)',
      '你 (nǐ)',
      '年龄 (niánlíng)',
      '拿 (ná)',
      '哪个 (nǎge)',
      '哪里 (nǎlǐ)',
      '难过 (nánguò)',
      '牛奶 (niúnǎi)',
      '朋友 (péngyǒu)',
      '苹果 (píngguǒ)',
      '钱 (qián)',
      '去 (qù)',
      '热 (rè)',
      '跑 (pǎo)',
      '请 (qǐng)',
      '坐 (zuò)',
      '学校 (xuéxiào)',
      '谁 (shéi)',
      '书 (shū)',
      '睡觉 (shuìjiào)',
      '水 (shuǐ)',
      '她说 (tā shuō)',
      '他 (tā)',
      '她 (tā)',
      '听 (tīng)',
      '他们 (tāmen)',
      '我们 (wǒmen)',
      '我 (wǒ)',
      '超市 (chāoshì)',
      '香蕉 (xiāngjiāo)',
      '小 (xiǎo)',
      '谢谢 (xièxiè)',
      '写 (xiě)',
      '学习 (xuéxí)',
      '需要 (xūyào)',
      '学 (xué)',
      '昨天 (zuótiān)',
      '再见 (zàijiàn)',
      '站 (zhàn)',
      '桌子 (zhuōzi)',
      '椅子 (yǐzi)',
      '这个 (zhège)',
      '怎么 (zěnme)',
      '做什么 (zuò shénme)',
      '找 (zhǎo)',
      '公园 (gōngyuán)',
      '工作 (gōngzuò)',
      '说什么 (shuō shénme)',
      '现在 (xiànzài)',
      '星期一 (xīngqīyī)',
      '学生 (xuéshēng)',
      '说话 (shuōhuà)',
      '说 (shuō)',
      '为什么 (wèishénme)',
      '什么时候 (shénme shíhou)',
      '那里 (nàlǐ)',
      '这里 (zhèlǐ)',
      '那个 (nàge)',
      '卖 (mài)',
      '面条 (miàntiáo)',
      '爸爸 (bàba)',
      '笔 (bǐ)',
      '是 (shì)',
      '喜欢 (xǐhuan)'
    ]
  },
  {
    id: 'mandarin-beginner',
    name: 'Mandarin-Beginner',
    isStudy: true,
    words: [
      '你好 nǐ hǎo [hello]',
      '谢谢 xièxiè [thank you]',
      '再见 zàijiàn [goodbye]',
      '请 qǐng [please]',
      '对不起 duìbùqǐ [sorry]',
      '是 shì [yes]',
      '不是 búshì [no]',
      '我 wǒ [I]',
      '你 nǐ [you]',
      '他 tā [he]',
      '她 tā [she]',
      '我们 wǒmen [we]',
      '他们 tāmen [they]',
      '吃 chī [eat]',
      '喝 hē [drink]',
      '看 kàn [look/watch]',
      '说 shuō [speak/say]',
      '听 tīng [listen]',
      '喜欢 xǐhuan [like]',
      '爱 ài [love]',
      '米饭 mǐfàn [rice]',
      '面条 miàntiáo [noodles]',
      '苹果 píngguǒ [apple]',
      '香蕉 xiāngjiāo [banana]',
      '牛奶 niúnǎi [milk]',
      '水 shuǐ [water]',
      '茶 chá [tea]',
      '咖啡 kāfēi [coffee]',
      '学校 xuéxiào [school]',
      '老师 lǎoshī [teacher]',
      '学生 xuéshēng [student]',
      '书 shū [book]',
      '笔 bǐ [pen]',
      '桌子 zhuōzi [table]',
      '椅子 yǐzi [chair]',
      '家 jiā [home/family]',
      '妈妈 māma [mom]',
      '爸爸 bàba [dad]',
      '朋友 péngyǒu [friend]',
      '狗 gǒu [dog]',
      '猫 māo [cat]',
      '车 chē [car]',
      '钱 qián [money]',
      '工作 gōngzuò [work]',
      '睡觉 shuìjiào [sleep]',
      '走 zǒu [walk]',
      '来 lái [come]',
      '去 qù [go]',
      '天气 tiānqì [weather]',
      '今天 jīntiān [today]',
      '明天 míngtiān [tomorrow]'
    ]
  },
  {
    id: 'mandarin-intermediate',
    name: 'Mandarin-Intermediate',
    isStudy: true,
    words: [
      '帮忙 bāngmáng [help]',
      '记得 jìde [remember]',
      '忘记 wàngjì [forget]',
      '明白 míngbai [understand]',
      '练习 liànxí [practice]',
      '问题 wèntí [problem/question]',
      '回答 huídá [answer]',
      '超市 chāoshì [supermarket]',
      '医院 yīyuàn [hospital]',
      '火车站 huǒchēzhàn [train station]',
      '机场 jīchǎng [airport]',
      '电影院 diànyǐngyuàn [cinema]',
      '生日快乐 shēngrì kuàilè [happy birthday]',
      '没问题 méi wèntí [no problem]',
      '太好了 tài hǎo le [great/awesome]',
      '怎么样 zěnmeyàng [how is it]',
      '几点 jǐ diǎn [what time]',
      '多少钱 duōshǎo qián [how much]',
      '打开 dǎkāi [open]',
      '关上 guānshàng [close]',
      '洗澡 xǐzǎo [take a shower]',
      '打电话 dǎ diànhuà [make a phone call]',
      '拍照 pāizhào [take a photo]',
      '等等 děngdeng [wait]',
      '小心 xiǎoxīn [be careful]',
      '成功 chénggōng [success]',
      '失败 shībài [failure]',
      '努力 nǔlì [effort/hard work]',
      '梦想 mèngxiǎng [dream]',
      '计划 jìhuà [plan]',
      '天气预报 tiānqì yùbào [weather forecast]',
      '交通灯 jiāotōngdēng [traffic light]',
      '身份证 shēnfènzhèng [ID card]',
      '信用卡 xìnyòngkǎ [credit card]',
      '菜单 càidān [menu]',
      '服务员 fúwùyuán [waiter/waitress]',
      '推荐 tuījiàn [recommend]',
      '味道怎么样 wèidào zěnmeyàng [how does it taste]',
      '太贵了 tài guì le [too expensive]',
      '打折 dǎzhé [discount]',
      '考试 kǎoshì [exam/test]',
      '复习 fùxí [review]',
      '提高 tígāo [improve]',
      '发音 fāyīn [pronunciation]',
      '语法 yǔfǎ [grammar]',
      '文化 wénhuà [culture]',
      '节日 jiérì [holiday]',
      '春节 chūnjié [Spring Festival]',
      '中秋节 zhōngqiūjié [Mid-Autumn Festival]',
      '龙年 lóngnián [Year of the Dragon]',
      '健康 jiànkāng [health]'
    ]
  },
  {
    id: 'vietnamese-beginner',
    name: 'Vietnamese-Beginner',
    isStudy: true,
    words: [
      'xin chào [hello]',
      'cảm ơn [thank you]',
      'tạm biệt [goodbye]',
      'làm ơn [please]',
      'xin lỗi [sorry]',
      'vâng [yes]',
      'không [no]',
      'tôi [I]',
      'bạn [you]',
      'anh ấy [he]',
      'cô ấy [she]',
      'chúng tôi [we]',
      'họ [they]',
      'ăn [eat]',
      'uống [drink]',
      'nhìn [look/watch]',
      'nói [speak/say]',
      'nghe [listen]',
      'thích [like]',
      'yêu [love]',
      'cơm [rice]',
      'mì [noodles]',
      'táo [apple]',
      'chuối [banana]',
      'sữa [milk]',
      'nước [water]',
      'trà [tea]',
      'cà phê [coffee]',
      'trường học [school]',
      'giáo viên [teacher]',
      'học sinh [student]',
      'sách [book]',
      'bút [pen]',
      'bàn [table]',
      'ghế [chair]',
      'nhà [home]',
      'mẹ [mom]',
      'bố [dad]',
      'bạn bè [friend]',
      'chó [dog]',
      'mèo [cat]',
      'xe [car]',
      'tiền [money]',
      'công việc [work]',
      'ngủ [sleep]',
      'đi bộ [walk]',
      'đến [come]',
      'đi [go]',
      'thời tiết [weather]',
      'hôm nay [today]',
      'ngày mai [tomorrow]'
    ]
  },
  {
    id: 'vietnamese-intermediate',
    name: 'Vietnamese-Intermediate',
    isStudy: true,
    words: [
      'giúp đỡ [help]',
      'nhớ [remember]',
      'quên [forget]',
      'hiểu [understand]',
      'luyện tập [practice]',
      'vấn đề [problem]',
      'câu trả lời [answer]',
      'siêu thị [supermarket]',
      'bệnh viện [hospital]',
      'ga tàu [train station]',
      'sân bay [airport]',
      'rạp chiếu phim [cinema]',
      'chúc mừng sinh nhật [happy birthday]',
      'không sao [no problem]',
      'tuyệt vời [great/awesome]',
      'thế nào [how is it]',
      'mấy giờ [what time]',
      'bao nhiêu tiền [how much]',
      'mở [open]',
      'đóng [close]',
      'tắm [take a shower]',
      'gọi điện [make a phone call]',
      'chụp ảnh [take a photo]',
      'chờ [wait]',
      'cẩn thận [be careful]',
      'thành công [success]',
      'thất bại [failure]',
      'nỗ lực [effort]',
      'giấc mơ [dream]',
      'kế hoạch [plan]',
      'dự báo thời tiết [weather forecast]',
      'đèn giao thông [traffic light]',
      'chứng minh thư [ID card]',
      'thẻ tín dụng [credit card]',
      'thực đơn [menu]',
      'nhân viên phục vụ [waiter]',
      'gợi ý [recommend]',
      'món ăn có ngon không [how does it taste]',
      'quá đắt [too expensive]',
      'giảm giá [discount]',
      'kỳ thi [exam]',
      'ôn tập [review]',
      'cải thiện [improve]',
      'phát âm [pronunciation]',
      'ngữ pháp [grammar]',
      'văn hóa [culture]',
      'lễ hội [holiday]',
      'Tết Nguyên Đán [Lunar New Year]',
      'Tết Trung Thu [Mid-Autumn Festival]',
      'Năm Rồng [Year of the Dragon]',
      'sức khỏe [health]'
    ]
  },
  {
    id: 'spanish-beginner',
    name: 'Spanish-Beginner',
    isStudy: true,
    words: [
      'hola [hello]',
      'gracias [thank you]',
      'adiós [goodbye]',
      'por favor [please]',
      'lo siento [sorry]',
      'sí [yes]',
      'no [no]',
      'yo [I]',
      'tú [you]',
      'él [he]',
      'ella [she]',
      'nosotros [we]',
      'ellos [they]',
      'comer [eat]',
      'beber [drink]',
      'mirar [look/watch]',
      'hablar [speak/say]',
      'escuchar [listen]',
      'gustar [like]',
      'amar [love]',
      'arroz [rice]',
      'fideos [noodles]',
      'manzana [apple]',
      'plátano [banana]',
      'leche [milk]',
      'agua [water]',
      'té [tea]',
      'café [coffee]',
      'escuela [school]',
      'maestro [teacher]',
      'estudiante [student]',
      'libro [book]',
      'lápiz [pen]',
      'mesa [table]',
      'silla [chair]',
      'casa [home]',
      'madre [mom]',
      'padre [dad]',
      'amigo [friend]',
      'perro [dog]',
      'gato [cat]',
      'coche [car]',
      'dinero [money]',
      'trabajo [work]',
      'dormir [sleep]',
      'caminar [walk]',
      'venir [come]',
      'ir [go]',
      'tiempo [weather]',
      'hoy [today]',
      'mañana [tomorrow]'
    ]
  },
  {
    id: 'spanish-intermediate',
    name: 'Spanish-Intermediate',
    isStudy: true,
    words: [
      'ayudar [help]',
      'recordar [remember]',
      'olvidar [forget]',
      'entender [understand]',
      'practicar [practice]',
      'problema [problem]',
      'respuesta [answer]',
      'supermercado [supermarket]',
      'hospital [hospital]',
      'estación de tren [train station]',
      'aeropuerto [airport]',
      'cine [cinema]',
      'feliz cumpleaños [happy birthday]',
      'no hay problema [no problem]',
      'genial [great/awesome]',
      '¿cómo está? [how is it]',
      '¿qué hora es? [what time is it]',
      '¿cuánto cuesta? [how much]',
      'abrir [open]',
      'cerrar [close]',
      'ducharse [take a shower]',
      'llamar por teléfono [make a phone call]',
      'tomar foto [take a photo]',
      'esperar [wait]',
      'cuidado [be careful]',
      'éxito [success]',
      'fracaso [failure]',
      'esfuerzo [effort]',
      'sueño [dream]',
      'plan [plan]',
      'pronóstico del tiempo [weather forecast]',
      'semáforo [traffic light]',
      'documento de identidad [ID card]',
      'tarjeta de crédito [credit card]',
      'menú [menu]',
      'camarero [waiter]',
      'recomendar [recommend]',
      '¿qué tal el sabor? [how does it taste]',
      'demasiado caro [too expensive]',
      'descuento [discount]',
      'examen [exam]',
      'repasar [review]',
      'mejorar [improve]',
      'pronunciación [pronunciation]',
      'gramática [grammar]',
      'cultura [culture]',
      'fiesta [holiday]',
      'Año Nuevo [New Year]',
      'Día de Muertos [Day of the Dead]',
      'Año del Dragón [Year of the Dragon]',
      'salud [health]'
    ]
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    isStudy: true,
    words: [
      'H₂O [water]',
      'O₂ [oxygen]',
      'NaCl [salt]',
      'CO₂ [carbon dioxide]',
      'Fe [iron]',
      'Au [gold]',
      'Ag [silver]',
      'Cu [copper]',
      'H [hydrogen]',
      'He [helium]',
      'N₂ [nitrogen]',
      'C [carbon]',
      'Pb [lead]',
      'Hg [mercury]',
      'Sn [tin]',
      'Al [aluminum]',
      'Ca [calcium]',
      'K [potassium]',
      'Na [sodium]',
      'Cl [chlorine]',
      'S [sulfur]',
      'P [phosphorus]',
      'Ne [neon]',
      'Ar [argon]',
      'Pt [platinum]',
      'combustion [fire reaction]',
      'acid [low pH substance]',
      'base [high pH substance]',
      'pH [acid-base scale]',
      'neutral [neither acid nor base]',
      'density [how compact matter is]',
      'carbon dioxide [CO₂]',
      'hydrogen peroxide [H₂O₂]',
      'ammonia [NH₃]',
      'reactant [before reaction]',
      'product [after reaction]',
      'catalyst [reaction helper]',
      'alkali metals [lithium sodium potassium]',
      'alkaline earth metals [beryllium magnesium calcium]',
      'halogens [fluorine chlorine bromine]',
      'noble gases [helium neon argon]',
      'transition metals [iron copper zinc]',
      'metalloids [silicon germanium arsenic]',
      'lanthanides [cerium europium gadolinium]',
      'actinides [uranium plutonium thorium]',
      'ionic bond [metal to nonmetal]',
      'covalent bond [nonmetal to nonmetal]',
      'metallic bond [metal to metal]',
      'hydrogen bond [water cohesion]',
      'orbital [s p d f]',
      'Avogadro\\\'s number [6.022 × 10²³]',
      'Arrhenius acid [proton donor]',
      'Arrhenius base [hydroxide donor]',
      'buffer [weak acid plus salt]',
      'pH scale [0 to 14 range]',
      'organic chemistry [hydrocarbon based]',
      'hydrocarbon [alkane alkene alkyne]',
      'alkane [saturated hydrocarbon]',
      'alkene [unsaturated hydrocarbon]',
      'alkyne [unsaturated hydrocarbon]',
      'alcohol [OH functional group]',
      'carboxylic acid [organic acid]',
      'ester [fruity smell compound]',
      'amine [NH₂ functional group]',
      'synthesis reaction [combination reaction]',
      'decomposition reaction [breaking apart]',
      'single replacement [substitution reaction]',
      'double replacement [metathesis reaction]',
      'combustion reaction [burning reaction]',
      'redox reaction [oxidation-reduction]',
      'oxidation [increase in charge]',
      'reduction [decrease in charge]',
      'oxidizing agent [causes oxidation]',
      'reducing agent [causes reduction]'
    ]
  },
  {
    id: 'us-history',
    name: 'US History',
    isStudy: true,
    words: [
      'Marbury v. Madison [1803 judicial review established]',
      'McCulloch v. Maryland [1819 upheld implied powers]',
      'Gibbons v. Ogden [1824 expanded commerce power]',
      'Dred Scott v. Sandford [1857 denied Black citizenship]',
      'Plessy v. Ferguson [1896 upheld separate but equal]',
      'Brown v. Board of Education [1954 ended school segregation]',
      'Korematsu v. United States [1944 upheld Japanese internment]',
      'Mapp v. Ohio [1961 exclusionary rule applied]',
      'Gideon v. Wainwright [1963 right to counsel guaranteed]',
      'Miranda v. Arizona [1966 Miranda warnings required]',
      'Tinker v. Des Moines [1969 protected student speech]',
      'New York Times v. United States [1971 limited prior restraint]',
      'Roe v. Wade [1973 legalized abortion nationwide]',
      'United States v. Nixon [1974 limited executive privilege]',
      'Regents of UC v. Bakke [1978 limited affirmative action]',
      'Texas v. Johnson [1989 protected flag burning]',
      'Bush v. Gore [2000 halted Florida recount]',
      'Citizens United v. FEC [2010 expanded corporate speech]',
      'Obergefell v. Hodges [2015 legalized same-sex marriage]',
      'Article I [legislative powers defined]',
      'Article II [executive powers defined]',
      'Article III [judicial powers defined]',
      'Article IV [state relations rules]',
      'Article V [amendment process outlined]',
      'Article VI [supremacy of Constitution]',
      'Article VII [ratification procedure set]',
      'Commerce Clause [regulates interstate commerce]',
      'Necessary and Proper Clause [implied powers allowed]',
      'Supremacy Clause [federal law supreme]',
      'Full Faith and Credit Clause [states honor other states]',
      'Privileges and Immunities Clause [protects interstate equality]',
      'General Welfare Clause [spending for common good]',
      'Contract Clause [limits state contract interference]',
      'Takings Clause [just compensation required]',
      'Establishment Clause [no official religion]',
      'Free Exercise Clause [protects religious practice]',
      'Free Speech Clause [protects expression rights]',
      'Free Press Clause [protects press freedom]',
      'Assembly Clause [protects peaceful assembly]',
      'Petition Clause [right to petition government]',
      'Search and Seizure Clause [bans unreasonable searches]',
      'Double Jeopardy Clause [no second prosecution]',
      'Self-Incrimination Clause [protects against self-accusation]',
      'Due Process Clause (5th) [federal due process guaranteed]',
      'Due Process Clause (14th) [state due process guaranteed]',
      'Equal Protection Clause [requires equal treatment]',
      'Confrontation Clause [face accusers in court]',
      'Assistance of Counsel Clause [guarantees legal counsel]',
      'Grand Jury Clause [requires serious-crime indictments]',
      'Cruel and Unusual Punishment Clause [limits harsh penalties]',
      '1st Amendment [1791 freedoms of speech and religion]',
      '2nd Amendment [1791 right to bear arms]',
      '3rd Amendment [1791 no forced quartering]',
      '4th Amendment [1791 no unreasonable searches]',
      '5th Amendment [1791 due process and self-incrimination]',
      '6th Amendment [1791 fair and speedy criminal trial]',
      '7th Amendment [1791 jury trial in civil cases]',
      '8th Amendment [1791 no cruel punishments]',
      '9th Amendment [1791 unlisted rights protected]',
      '10th Amendment [1791 powers reserved to states]',
      '11th Amendment [1795 limits suits against states]',
      '12th Amendment [1804 revised electoral college]',
      '13th Amendment [1865 abolished slavery]',
      '14th Amendment [1868 citizenship and equal protection]',
      '15th Amendment [1870 protected voting by race]',
      '16th Amendment [1913 authorized income tax]',
      '17th Amendment [1913 direct election of senators]',
      '18th Amendment [1919 prohibition of alcohol]',
      '19th Amendment [1920 womens suffrage guaranteed]',
      '20th Amendment [1933 changed inauguration dates]',
      '21st Amendment [1933 repealed prohibition]',
      '22nd Amendment [1951 limited presidential terms]',
      '23rd Amendment [1961 DC presidential electors]',
      '24th Amendment [1964 banned poll taxes]',
      '25th Amendment [1967 presidential succession rules]',
      '26th Amendment [1971 voting age set to 18]',
      '27th Amendment [1992 delayed congressional pay raises]'
    ]
  },
  {
    id: 'landforms',
    name: 'Landforms',
    isStudy: true,
    words: [
      'Mountain [high, steep land]',
      'Hill [small raised area of land]',
      'Plain [large flat area of land]',
      'Plateau [high flat land]',
      'Valley [low land between hills or mountains]',
      'Canyon [deep, narrow valley with steep sides]',
      'Cliff [high, steep rock face]',
      'River [large flowing body of water]',
      'Lake [large body of water surrounded by land]',
      'Delta [triangle-shaped land at a rivers mouth]',
      'Island [land completely surrounded by water]',
      'Peninsula [land almost surrounded by water]',
      'Bay [water partly surrounded by land]',
      'Gulf [large bay-like body of water]',
      'Coast [land along the ocean]',
      'Beach [sandy or pebbly shore]',
      'Dune [hill of sand shaped by wind]',
      'Desert [very dry land with little rain]',
      'Forest [large area covered with trees]',
      'Jungle [thick, warm, rainy forest]',
      'Swamp [wet, spongy land with plants]',
      'Wetland [land that is often covered with water]',
      'Glacier [slow-moving river of ice]',
      'Volcano [mountain that can erupt lava]',
      'Crater [bowl-shaped hole in the ground]',
      'Fjord [narrow sea inlet between steep cliffs]',
      'Lagoon [shallow water separated from sea]',
      'Harbor [sheltered place for ships]',
      'Oasis [green area in a desert]',
      'Mesa [flat-topped hill with steep sides]'
    ]
  },
  {
    id: 'human-body',
    name: 'Human Body',
    isStudy: true,
    words: [
      'Circulatory system [moves blood around body]',
      'Respiratory system [brings in oxygen to body]',
      'Digestive system [breaks down food for energy]',
      'Nervous system [controls body and senses]',
      'Skeletal system [supports and protects body]',
      'Muscular system [helps body move]',
      'Immune system [defends against germs]',
      'Endocrine system [uses hormones to send signals]',
      'Urinary system [removes liquid waste]',
      'Reproductive system [helps create new life]',
      'Integumentary system [protects body with skin]',
      'Brain [controls thoughts and actions]',
      'Spinal cord [carries messages to and from brain]',
      'Nerves [send signals all over body]',
      'Heart [pumps blood through body]',
      'Lungs [take in oxygen, release carbon dioxide]',
      'Stomach [starts breaking down food]',
      'Small intestine [absorbs nutrients from food]',
      'Large intestine [takes water, forms waste]',
      'Liver [cleans blood and processes nutrients]',
      'Pancreas [helps digest food and control sugar]',
      'Kidneys [filter waste from blood]',
      'Bladder [stores urine before it leaves body]',
      'Skin [protects body and keeps germs out]',
      'Bones [give body shape and support]',
      'Muscles [pull bones to move body]',
      'Eyes [see light and color]',
      'Ears [hear sounds and help balance]',
      'Nose [smells and helps with taste]',
      'Tongue [tastes and helps with speech]',
      'Teeth [cut and grind food]',
      'Brain [controls body and thinking]',
      'Heart [pumps blood nonstop]',
      'Lungs [swap oxygen and carbon dioxide]',
      'Stomach [mixes food with acids]',
      'Liver [cleans blood and helps digestion]',
      'Kidneys [filter blood and make urine]',
      'Pancreas [controls blood sugar, aids digestion]',
      'Small intestine [absorbs tiny food particles]',
      'Large intestine [removes water, forms stool]',
      'Bladder [stores urine]',
      'Gallbladder [stores bile for fat digestion]',
      'Spleen [helps fight germs, filters blood]',
      'Skin [shields body and controls temperature]',
      'Esophagus [moves food to stomach]',
      'Trachea [carries air to lungs]',
      'Diaphragm [helps lungs move air]',
      'Thyroid [controls how fast body uses energy]',
      'Ovaries [make eggs and hormones]',
      'Testes [make sperm and hormones]',
      'Uterus [holds a growing baby]',
      'Bone marrow [makes blood cells]',
      'Cornea [clear front window of eye]',
      'Retina [senses light in eye]',
      'Eardrum [vibrates to pass along sound]'
    ]
  },
  {
    id: 'space',
    name: 'Space',
    isStudy: true,
    words: [
      'Sun [star at center of our solar system]',
      'Mercury [small hot inner planet]',
      'Venus [cloudy, very hot planet]',
      'Earth [our home, blue planet]',
      'Mars [red planet with thin air]',
      'Jupiter [largest gas giant planet]',
      'Saturn [gas giant with bright rings]',
      'Uranus [tilted ice giant planet]',
      'Neptune [far, cold blue planet]',
      'Planet [large body orbiting a star]',
      'Dwarf planet [small round body orbiting sun]',
      'Moon [natural satellite of a planet]',
      'Asteroid [rocky object orbiting the sun]',
      'Comet [icy body with glowing tail]',
      'Meteoroid [small space rock]',
      'Meteor [space rock burning in atmosphere]',
      'Meteorite [space rock that hits the ground]',
      'Orbit [path an object follows around another]',
      'Ellipse [oval-shaped orbit path]',
      'Gravity [force that pulls objects together]',
      'Satellite [object that orbits a planet]',
      'Space probe [robot sent to explore space]',
      'Space station [place where astronauts live in orbit]',
      'Galaxy [huge group of stars and planets]',
      'Milky Way [galaxy that holds our solar system]',
      'Lagrange point [spot where gravity balances orbits]',
      'L1 point [gravity-balance point between two bodies]',
      'L2 point [gravity-balance point behind a body]',
      'L3 point [gravity-balance point opposite side of sun]',
      'L4 point [stable gravity point ahead in orbit]',
      'L5 point [stable gravity point behind in orbit]',
      'Asteroid belt [ring of asteroids between Mars and Jupiter]',
      'Kuiper Belt [region of icy bodies beyond Neptune]',
      'Oort Cloud [distant shell of icy objects]'
    ]
  },
  {
    id: 'ancient-world',
    name: 'Ancient World',
    isStudy: true,
    words: [
      'Ancient Egypt [built pyramids and hieroglyphs]',
      'Mesopotamia [created first known writing]',
      'Ancient Sumer [built early cities and ziggurats]',
      'Babylon [famous law code and hanging gardens]',
      'Assyria [strong army and iron weapons]',
      'Ancient Greece [started democracy and philosophy]',
      'Sparta [military-focused city-state]',
      'Athens [center of art and learning]',
      'Ancient Rome [built roads and strong laws]',
      'Byzantine Empire [kept Roman law and learning alive]',
      'Ancient China [invented paper and compass]',
      'Shang Dynasty [early Chinese writing and bronze]',
      'Zhou Dynasty [Mandate of Heaven idea]',
      'Qin Dynasty [first united Chinese empire]',
      'Han Dynasty [expanded trade on Silk Road]',
      'Indus Valley [planned cities with drains]',
      'Ancient India (Maurya) [spread Buddhism]',
      'Gupta Empire [advances in math and medicine]',
      'Ancient Persia [built huge empire with roads]',
      'Phoenicia [expert sailors and alphabet]',
      'Mayan civilization [complex calendar and pyramids]',
      'Aztec Empire [floating gardens and temples]',
      'Inca Empire [mountain roads and terraces]',
      'Ancient Israel [monotheistic faith traditions]',
      'Carthage [powerful trading sea empire]',
      'Hittites [early ironworking skills]',
      'Olmec [giant stone head sculptures]',
      'Minoan civilization [sea trade and palaces]',
      'Mycenaean civilization [early Greek warriors]',
      'Song Dynasty China [gunpowder and printing]'
    ]
  },
  {
    id: 'geopolitics',
    name: 'Geopolitics',
    isStudy: true,
    words: [
      'American Revolution [17751783 colonies win independence]',
      'French Revolution [17891799 overthrew French monarchy]',
      'War of 1812 [18121815 US vs Britain conflict]',
      'MexicanAmerican War [18461848 US gains southwest lands]',
      'US Civil War [18611865 North vs South over slavery]',
      'SpanishAmerican War [1898 US gains overseas territories]',
      'World War I [19141918 global war in Europe]',
      'Russian Revolution [1917 tsar overthrown, USSR formed]',
      'Treaty of Versailles [1919 punished Germany after WWI]',
      'Great Depression [19291939 worldwide economic crisis]',
      'World War II [19391945 global war against Axis powers]',
      'United Nations formed [1945 world group for peace]',
      'Marshall Plan [19481952 US helps rebuild Europe]',
      'Cold War begins [late 1940s USUSSR rivalry]',
      'Korean War [19501953 North vs South Korea]',
      'Cuban Missile Crisis [1962 USUSSR nuclear standoff]',
      'Vietnam War [19551975 conflict in Southeast Asia]',
      'Civil Rights Act [1964 US law banning segregation]',
      'Detente period [1970s eased Cold War tensions]',
      'Soviet Union collapses [1991 ends Cold War era]',
      'Gulf War [19901991 US-led force frees Kuwait]',
      'Good Friday Agreement [1998 peace in Northern Ireland]',
      '9/11 attacks [2001 terror attack on United States]',
      'War in Afghanistan [20012021 long US-led conflict]',
      'Iraq War [20032011 US-led invasion of Iraq]',
      'Paris Climate Agreement [2015 global climate pledge]',
      'Brexit referendum [2016 UK votes to leave EU]',
      'Confederation of Canada [1867 provinces unite as nation]',
      'Rebellion of 1837 [1837 armed uprising for reform]',
      'British North America Act [1867 created Dominion of Canada]',
      'Red River Rebellion [18691870 Mtis resist land loss]',
      'Klondike Gold Rush [18961899 massive gold migration]',
      'Fall of Constantinople [1453 Ottomans end Byzantine Empire]',
      'Protestant Reformation [1517 Luther challenges Catholic Church]',
      'Peace of Westphalia [1648 ended Thirty Years War]',
      'Glorious Revolution [1688 limited monarchy in England]',
      'Seven Years War [17561763 global colonial conflict]',
      'Napoleonic Wars [18031815 Napoleon conquers Europe]',
      'Unification of Italy [1861 multiple states form Italy]',
      'Unification of Germany [1871 Bismarck creates German Empire]',
      'Fall of Berlin Wall [1989 end of Cold War division]',
      'Mongol invasion of Rus [12371240 Mongols conquer Russia]',
      'Time of Troubles [15981613 chaos and foreign invasion]',
      'Romanov Dynasty begins [1613 ended time of troubles]',
      'Decembrist Revolt [1825 nobles tried to end autocracy]',
      'Crimean War [18531856 Russia vs European powers]',
      'October Revolution [1917 Bolsheviks seize power]',
      'all of Han Dynasty [220 AD empire splits into warlord states]',
      'Tang Dynasty golden age [618907 poetry and trade peak]',
      'Mongol conquest of China [1279 Kublai Khan forms Yuan Dynasty]',
      'Ming Dynasty founded [1368 Han Chinese overthrow Mongols]',
      'Opium Wars [18391860 Britain forces trade openings]',
      'Boxer Rebellion [1900 uprising against foreign influence]',
      'Meiji Restoration [1868 ended shogun rule, modernized Japan]',
      'Battle of Sekigahara [1600 unified Japan under Tokugawa]',
      'Sino-Japanese War [18941895 Japan gains Taiwan]',
      'Russo-Japanese War [19041905 Japan defeats Russia]',
      'Treaty of Kanagawa [1854 US opens Japan to trade]',
      'Inca Empire founded [1438 expanded across Andes]',
      'Spanish conquest of Inca [15321572 Pizarro ends empire]',
      'Brazilian independence [1822 Portugal colony becomes empire]',
      'War of the Triple Alliance [18641870 Paraguay vs neighbors]',
      'Chaco War [19321935 Bolivia vs Paraguay over land]',
      'Battle of Tours [732 stopped Muslim advance in Europe]',
      'Seljuk Turks conquer Persia [1037 expanded Islamic empire]',
      'Mongol sack of Baghdad [1258 ended Abbasid Caliphate]',
      'Ottoman conquest of Constantinople [1453 became Ottoman capital]',
      'Arab Revolt [1916 against Ottoman rule in Arabia]',
      'Iranian Revolution [1979 overthrew monarchy, created Islamic Republic]',
      'Rise of Kingdom of Aksum [100 AD powerful Ethiopian trading empire]',
      'Ghana Empire peak [8001100 gold and salt trade]',
      'Mali Empire under Mansa Musa [13121337 richest king ever]',
      'Zulu Kingdom expansion [18161879 Shakas military reforms]',
      'Berlin Conference [18841885 Europeans divide Africa]',
      'Scramble for Africa [1880s1914 colonial land grab]'
    ]
  },
  {
    id: 'pioneers',
    name: 'Pioneers',
    isStudy: true,
    words: [
      'Christopher Columbus [voyages linking Europe and Americas]',
      'Ferdinand Magellan [crew first sailed around world]',
      'Marco Polo [described travels to Asia]',
      'Lewis and Clark [explored western United States]',
      'Sacagawea [guided explorers in the West]',
      'Neil Armstrong [first person to walk on moon]',
      'Yuri Gagarin [first human in space]',
      'Amelia Earhart [pioneering woman pilot]',
      'Isaac Newton [laws of motion and gravity]',
      'Galileo Galilei [improved telescope, studied planets]',
      'Albert Einstein [theories of relativity]',
      'Marie Curie [discovered important radioactive elements]',
      'Nikola Tesla [pioneered alternating current power]',
      'Thomas Edison [improved light bulb and devices]',
      'Alexander Graham Bell [invented practical telephone]',
      'Charles Darwin [theory of evolution by natural selection]',
      'Gregor Mendel [discoveries in genetics with peas]',
      'Rachel Carson [sparked modern environmental movement]',
      'Leonardo da Vinci [Renaissance art and inventions]',
      'Michelangelo [famous sculptures and paintings]',
      'Ludwig van Beethoven [influential classical music]',
      'Wolfgang Amadeus Mozart [prolific composer]',
      'Pablo Picasso [pioneered modern art styles]',
      'Frida Kahlo [iconic self-portraits and identity themes]',
      'Harriet Tubman [led enslaved people to freedom]',
      'Frederick Douglass [abolitionist writer and speaker]',
      'Susan B. Anthony [fought for womens voting rights]',
      'Mahatma Gandhi [led nonviolent independence movement]',
      'Martin Luther King Jr. [led US civil rights movement]',
      'Rosa Parks [sparked bus boycott for equality]',
      'Nelson Mandela [fought apartheid, became president]',
      'Cesar Chavez [organized farm workers for rights]',
      'Malala Yousafzai [stands up for girls education]'
    ]
  },
  {
    id: 'mythology',
    name: 'Mythology',
    isStudy: true,
    words: [
      'Zeus [Greece king of gods, sky and thunder]',
      'Hera [Greece queen of gods, marriage protector]',
      'Poseidon [Greece god of sea and earthquakes]',
      'Demeter [Greece goddess of agriculture and harvest]',
      'Hades [Greece god of underworld and dead]',
      'Athena [Greece goddess of wisdom and war strategy]',
      'Apollo [Greece god of sun, music and prophecy]',
      'Artemis [Greece goddess of hunt and moon]',
      'Ares [Greece god of war and violence]',
      'Aphrodite [Greece goddess of love and beauty]',
      'Hermes [Greece god of travel and messengers]',
      'Hephaestus [Greece god of fire and blacksmiths]',
      'Dionysus [Greece god of wine and parties]',
      'Hestia [Greece goddess of hearth and home]',
      'Cronus [Greece Titan ruler of golden age]',
      'Rhea [Greece Titan mother of Olympians]',
      'Oceanus [Greece Titan god of ocean rivers]',
      'Atlas [Greece Titan holds up the sky]',
      'Prometheus [Greece Titan stole fire for humans]',
      'Gaia [Greece primordial earth mother]',
      'Uranus [Greece primordial sky father]',
      'Typhon [Greece monstrous storm giant]',
      'Cyclops [Greece one-eyed giants, weapon makers]',
      'Minotaur [Greece bull-headed man-eating monster]',
      'Medusa [Greece snake-haired monster turns to stone]',
      'Cerberus [Greece three-headed guard dog of underworld]',
      'Pegasus [Greece winged horse from Medusa]',
      'Chimera [Greece fire-breathing lion-goat-snake]',
      'Hydra [Greece multi-headed regenerating serpent]',
      'Sphinx [Greece riddle-asking lion-woman]',
      'Hercules [Greece hero of twelve labors]',
      'Achilles [Greece warrior with invincible heel]',
      'Odysseus [Greece clever king of Ithaca]',
      'Perseus [Greece slayer of Medusa]',
      'Thor [Norse god of thunder and hammer]',
      'Odin [Norse king of gods, wisdom seeker]',
      'Loki [Norse trickster god and shapeshifter]',
      'Freyja [Norse goddess of love and war]',
      'Freyr [Norse god of fertility and peace]',
      'Tyr [Norse god of war and justice]',
      'Fenrir [Norse giant wolf, Ragnarok destroyer]',
      'Jormungandr [Norse world-encircling serpent]',
      'Valkyries [Norse warrior women choosers of slain]',
      'Yggdrasil [Norse world tree connecting realms]',
      'Ra [Egypt sun god and creator]',
      'Osiris [Egypt god of afterlife and resurrection]',
      'Isis [Egypt goddess of magic and motherhood]',
      'Anubis [Egypt jackal god of embalming]',
      'Horus [Egypt falcon god of kingship]',
      'Set [Egypt god of chaos and storms]',
      'Thoth [Egypt ibis god of writing and knowledge]',
      'Bastet [Egypt cat goddess of protection]',
      'Amun [Egypt hidden god of creation]',
      'Sphinx [Egypt lion-bodied guardian of pyramids]',
      'Anansi [Africa West spider trickster storyteller]',
      'Olorun [Yoruba Nigeria sky creator god]',
      'Shango [Yoruba Nigeria thunder and justice god]',
      'Ogun [Yoruba Nigeria iron and war god]',
      'Mami Wata [Africa water spirit of wealth and beauty]',
      'Amaterasu [Japan sun goddess ancestor]',
      'Susanoo [Japan storm god brother of sun]',
      'Izanagi [Japan creator god of creation]',
      'Izanami [Japan creator goddess of death]',
      'Kitsune [Japan fox spirits shapeshifters]',
      'Kappa [Japan water imp with turtle shell]',
      'Tengu [Japan bird-like mountain demons]',
      'Jade Emperor [China supreme ruler of heaven]',
      'Nuwa [China serpent goddess created humans]',
      'Pangu [China giant separated earth and sky]',
      'Sun Wukong [China Monkey King trickster hero]',
      'Dragons [China wise rain-bringing serpents]',
      'Nine-tailed fox [China seductive shape-shifting spirit]',
      'Yama [India Hindu god of death and justice]',
      'Shiva [India destroyer and transformer god]',
      'Vishnu [India preserver god with avatars]',
      'Lakshmi [India goddess of wealth and prosperity]',
      'Hanuman [India monkey god loyal hero]',
      'Garuda [India eagle mount of Vishnu]',
      'Kali [India fierce goddess of time and destruction]',
      'Tezcatlipoca [Aztec Mexico smoking mirror god]',
      'Quetzalcoatl [Aztec Mexico feathered serpent creator]',
      'Huitzilopochtli [Aztec Mexico war and sun god]',
      'Xipe Totec [Aztec Mexico renewal god flayed skin]',
      'Jaguar warriors [Aztec Mexico elite fighter order]',
      'Inti [Inca Peru sun god emperor ancestor]',
      'Viracocha [Inca Peru creator god of sea]',
      'Mama Quilla [Inca Peru moon goddess]',
      'Thor Heyerdahl [modern explorer of ancient voyages]',
      'Anansi [Caribbean spider folklore hero]',
      'Slenderman [modern creepypasta tall faceless figure]',
      'Thunderbird [Native American massive storm-bringing bird]',
      'Wendigo [Native American cannibalistic ice spirit monster]',
      'Horned Serpent [Native American water guardian serpent]',
      'Skinwalker [Navajo shapeshifting witch]',
      'Piasa Bird [Illinois Native winged cat-like beast]',
      'Water Panther [Ojibwe underwater panther spirit]',
      'Raven [Pacific Northwest trickster creator bird]',
      'Coyote [Native American trickster culture hero]',
      'Spider Woman [Hopi creator weaver of world]',
      'Kokopelli [Hopi fertility flute player]',
      'Iktomi [Lakota spider trickster]',
      'Gluskap [Algonquin culture hero giant]',
      'Nanabozho [Ojibwe rabbit trickster]',
      'Flying Head [Iroquois severed head monster]',
      'Ogopogo [Inuit Canada lake serpent monster]',
      'Pukwudgie [Wampanoag spiky-backed troll]',
      'Gitchie Manitou [Ojibwe great spirit creator]',
      'Estsanatlehi [Navajo changing woman goddess]',
      'Spider Grandmother [Native Southwest creator weaver]',
      'Maheo [Cheyenne all-father creator]',
      'Unktehila [Lakota water serpent monsters]',
      'Awonawilona [Zuni creator of all things]',
      'Lodge Boy [Native twins culture heroes]',
      'Horned Water Snake [Seminole underwater horned beast]',
      'Gitchi Manitou [Algonquin great spirit of life]',
      'Napi [Blackfoot trickster old man]',
      'Tawa [Hopi sun god creator]',
      'White Buffalo Calf Woman [Lakota sacred pipe bringer]',
      'Shango [Yoruba Africa thunder axe god]',
      'Ogun [Yoruba Africa iron war god]',
      'Olorun [Yoruba Africa sky supreme creator]',
      'Eshu [Yoruba Africa trickster messenger]',
      'Yemoja [Yoruba Africa ocean mother goddess]',
      'Oshun [Yoruba Africa river love goddess]',
      'Obatala [Yoruba Africa white cloth creator]',
      'Nyame [Ashanti Africa sky god]',
      'Anansi [Ashanti West Africa spider storyteller]',
      'Grootslang [South Africa elephant-snake treasure guardian]',
      'Impundulu [Zulu South Africa lightning bird vampire]',
      'Sasabonsam [Ghana forest vampire bat demon]',
      'Tokoloshe [Zulu South Africa evil household imp]',
      'Mami Wata [West Africa seductive water spirit]',
      'Adro [Luganda Uganda sky and earth god]',
      'Mulungu [East Africa supreme creator god]',
      'Nyami Nyami [Zambia Zambezi river god serpent]',
      'Amadioha [Igbo Nigeria thunder justice god]',
      'Ala [Igbo Nigeria earth mother goddess]',
      'Legba [Fon Benin crossroads trickster]',
      'Quetzalcoatl [Aztec Mexico feathered serpent creator]?',
      'Tlloc [Aztec Mexico rain thunder god]',
      'Xochiquetzal [Aztec Mexico flowers love goddess]',
      'Coatlicue [Aztec Mexico earth skirt-of-snakes]',
      'Chalchiuhtlicue [Aztec Mexico jade water goddess]',
      'Tlaltecuhtli [Aztec Mexico earth monster alligator]',
      'Cipactli [Aztec Mexico primordial sea monster]',
      'Itzpapalotl [Aztec Mexico obsidian butterfly demon]',
      'Xipe Totec [Aztec Mexico flayed renewal god]',
      'Mictlantecuhtli [Aztec Mexico skeleton death god]',
      'Hunahpu [Maya twin hero ballplayer]?',
      'Xbalanque [Maya twin hero underworld survivor]',
      'Itzamna [Maya creator sky god]',
      'Ix Chel [Maya moon medicine goddess]',
      'Kukulkan [Maya feathered serpent wind god]',
      'Buluc Chabtan [Maya war star demon]',
      'Camazotz [Maya bat death god]',
      'Ah Puch [Maya skull-faced death lord]',
      'Inti [Inca Peru sun god emperor ancestor]',
      'Viracocha [Inca Peru sea creator god]',
      'Pachamama [Inca Peru earth mother goddess]',
      'Supay [Inca Peru underworld demon]',
      'Illapa [Inca Peru thunder lightning god]',
      'Mama Cocha [Inca Peru sea mother goddess]',
      'Apus [Inca Peru sacred mountain spirits]',
      'Amaru [Inca Peru earth serpent dragon]',
      'Maui [Polynesia demigod fisherman island fisher]?',
      'Pele [Hawaii volcano fire goddess]',
      'Kane [Hawaiian life light god]',
      'Ku [Hawaiian war god]',
      'Lono [Hawaiian peace fertility god]',
      'Hi\'iaka [Hawaiian Pele\'s dancer sister]',
      'Ranginui [Maori New Zealand sky father]',
      'Papatuanuku [Maori New Zealand earth mother]',
      'Tane Mahuta [Maori New Zealand forest creator]',
      'Tawhiri [Maori New Zealand storm god]',
      'Hine-nui-te-po [Maori New Zealand death goddess]',
      'Rainbow Serpent [Australian Aboriginal water creator]',
      'Baiame [Australian Aboriginal sky father]',
      'Wandjina [Australian Aboriginal rain cloud spirits]',
      'Bunyip [Australian Aboriginal swamp monster]',
      'Mimi [Australian Aboriginal skinny cave spirits]',
      'Tiddalik [Australian Aboriginal frog caused drought]',
      'Guanyin [China Buddhist mercy goddess]',
      'Houyi [China archer shot down suns]',
      'Chang\'e [China moon lady rabbit companion]',
      'Nezha [China child warrior god]',
      'Erlang Shen [China three-eyed thunder deity]',
      'White Tiger [China west guardian constellation]',
      'Azure Dragon [China east guardian constellation]',
      'Vermilion Bird [China south guardian constellation]',
      'Black Tortoise [China north guardian constellation]',
      'Nian [China New Year monster scared by red]',
      'Kitsune [Japanese fox spirit shapeshifter]',
      'Tengu [Japanese bird demon warrior trainer]',
      'Kappa [Japanese river imp cucumber lover]',
      'Oni [Japanese horned demon club wielder]',
      'Yuki-onna [Japanese snow woman spirit]',
      'Tanuki [Japanese raccoon dog trickster]',
      'Nurikabe [Japanese invisible wall spirit]',
      'Amaterasu [Japanese sun goddess cave hider]',
      'Susanoo [Japanese storm sea god slayer]',
      'Izanagi [Japanese creation stirring god]',
      'Izanami [Japanese creation death goddess]',
      'Brahma [India Hindu creator god]?',
      'Shiva [India Hindu destroyer dancer]',
      'Vishnu [India Hindu preserver incarnator]',
      'Lakshmi [India Hindu wealth lotus goddess]',
      'Saraswati [India Hindu knowledge music goddess]',
      'Ganesha [India Hindu elephant-head obstacle remover]',
      'Hanuman [India Hindu monkey strength devotee]',
      'Kali [India Hindu fierce time destroyer]',
      'Krishna [India Hindu avatar playful prince]',
      'Rama [India Hindu ideal king warrior]',
      'Parvati [India Hindu Shiva\'s devoted wife]',
      'Kartikeya [India Hindu war god peacock rider]',
      'Durga [India Hindu demon-slaying warrior goddess]',
      'Garuda [India Hindu eagle Vishnu mount]',
      'Naga [India serpent people guardians]',
      'Ravana [India demon king Lanka ruler]',
      'Asuras [India powerful anti-gods]',
      'Rakshasas [India shape-shifting demons]',
      'Yama [India Hindu death judge]',
      'Indra [India Vedic king of gods thunder]'
    ]
  },
];
