export const STUDY_WORDS_1: { id: string; name: string; isStudy: boolean; words: string[] }[] = [
  {
    id: 'chemistry-easy',
    name: 'Chemistry - Easy',
    isStudy: true,
    words: [
      'H₂O [water]',
      'O₂ [oxygen]',
      'NaCl [salt]',
      'CO₂ [carbon dioxide]',
      'Fe [iron]',
      'Au [gold]',
      'Ag [silver]',
      'Cu [copper]',
      'H [hydrogen]',
      'He [helium]',
      'N₂ [nitrogen]',
      'C [carbon]',
      'Pb [lead]',
      'Hg [mercury]',
      'Sn [tin]',
      'Al [aluminum]',
      'Ca [calcium]',
      'K [potassium]',
      'Na [sodium]',
      'Cl [chlorine]',
      'S [sulfur]',
      'P [phosphorus]',
      'Ne [neon]',
      'Ar [argon]',
      'Pt [platinum]',
      'solid [state of matter]',
      'liquid [state of matter]',
      'gas [state of matter]',
      'melting [phase change]',
      'freezing [phase change]',
      'evaporation [phase change]',
      'condensation [phase change]',
      'boiling [phase change]',
      'atom [basic particle]',
      'molecule [bonded atoms]',
      'element [basic substance]',
      'compound [chemical combination]',
      'mixture [physical combination]',
      'solution [homogeneous mixture]',
      'proton [subatomic particle]',
      'neutron [subatomic particle]',
      'electron [subatomic particle]',
      'nucleus [atom core]',
      'periodic table [element organizer]',
      'chemical reaction [change in matter]',
      'rust [iron oxide]',
      'photosynthesis [plant chemistry]',
      'combustion [fire reaction]',
      'acid [low pH substance]',
      'base [high pH substance]',
      'pH [acid-base scale]',
      'neutral [neither acid nor base]',
      'density [how compact matter is]',
      'mass [measured in grams]',
      'volume [measured in liters]',
      'temperature [measured in degrees]',
      'thermometer [lab instrument]',
      'beaker [lab equipment]',
      'test tube [lab equipment]',
      'graduated cylinder [lab equipment]',
      'goggles [lab safety]',
      'lab coat [lab safety]',
      'fire extinguisher [lab safety]',
      'chemical formula [substance shorthand]',
      'physical change [reversible change]',
      'chemical change [irreversible change]',
      'dissolving [going into solution]',
      'filtration [separation method]',
      'distillation [separation method]',
      'metal [element type]',
      'nonmetal [element type]',
      'gas [matter state]',
      'oxygen [O on periodic table]',
      'carbon dioxide [CO₂]',
      'baking soda [sodium bicarbonate]',
      'vinegar [acetic acid]',
      'hydrogen peroxide [H₂O₂]',
      'ammonia [NH₃]',
      'table sugar [sucrose]',
      'stainless steel [iron alloy]',
      'bronze [metal alloy]',
      'brass [metal alloy]',
      'diamond [carbon form]',
      'graphite [carbon form]',
      'litmus paper [pH test strip]',
      'indicator [acid-base tester]',
      'Bunsen burner [lab equipment]',
      'flask [lab equipment]',
      'magnet [magnetic material]',
      'conductor [electrical property]',
      'insulator [electrical property]',
      'flammable [safety warning]',
      'toxic [safety warning]',
      'corrosive [safety warning]',
      'conservation of mass [chemistry law]',
      'reactant [before reaction]',
      'product [after reaction]',
      'catalyst [reaction helper]',
      'energy [measured in joules]',
      'exothermic [reaction type]'
    ]
  },
  {
    id: 'chemistry-intermediate',
    name: 'Chemistry - Intermediate',
    isStudy: true,
    words: [
      'alkali metals [lithium sodium potassium]',
      'alkaline earth metals [beryllium magnesium calcium]',
      'halogens [fluorine chlorine bromine]',
      'noble gases [helium neon argon]',
      'transition metals [iron copper zinc]',
      'metalloids [silicon germanium arsenic]',
      'lanthanides [cerium europium gadolinium]',
      'actinides [uranium plutonium thorium]',
      'ionic bond [metal to nonmetal]',
      'covalent bond [nonmetal to nonmetal]',
      'metallic bond [metal to metal]',
      'hydrogen bond [water cohesion]',
      'van der Waals [London dispersion]',
      'polar covalent [partial charges]',
      'electronegativity [Pauling scale]',
      'valence electrons [bonding electrons]',
      'electron configuration [orbital filling order]',
      'orbital [s p d f]',
      'quantum numbers [n l ml ms]',
      'Aufbau principle [orbital filling rule]',
      'Hund\\\'s rule [parallel spin first]',
      'Pauli exclusion [opposite spins only]',
      'mole [Avogadro\\\'s number]',
      'molar mass [molecular weight]',
      'molarity [solution concentration]',
      'stoichiometry [mole ratios]',
      'limiting reagent [determines product amount]',
      'excess reagent [not fully consumed]',
      'percent yield [reaction efficiency]',
      'empirical formula [reduced formula]',
      'molecular formula [true formula]',
      'Avogadro\\\'s number [6.022 × 10²³]',
      'Arrhenius acid [proton donor]',
      'Arrhenius base [hydroxide donor]',
      'Brønsted-Lowry acid [H⁺ giver]',
      'Brønsted-Lowry base [H⁺ receiver]',
      'Lewis acid [empty orbital species]',
      'Lewis base [lone pair species]',
      'strong acid [HCl HNO₃ H₂SO₄]',
      'weak acid [acetic acid HF]',
      'buffer [weak acid plus salt]',
      'titration [neutralization measurement]',
      'equivalence point [neutralization complete]',
      'pH scale [0 to 14 range]',
      'organic chemistry [hydrocarbon based]',
      'hydrocarbon [alkane alkene alkyne]',
      'alkane [saturated hydrocarbon]',
      'alkene [unsaturated hydrocarbon]',
      'alkyne [unsaturated hydrocarbon]',
      'functional group [determines properties]',
      'alcohol [OH functional group]',
      'carboxylic acid [organic acid]',
      'ester [fruity smell compound]',
      'amine [NH₂ functional group]',
      'polymer [plastic and rubber]',
      'monomer [polymer building block]',
      'isomer [structural variation]',
      'synthesis reaction [combination reaction]',
      'decomposition reaction [breaking apart]',
      'single replacement [substitution reaction]',
      'double replacement [metathesis reaction]',
      'combustion reaction [burning reaction]',
      'redox reaction [oxidation-reduction]',
      'oxidation [increase in charge]',
      'reduction [decrease in charge]',
      'oxidizing agent [causes oxidation]',
      'reducing agent [causes reduction]',
      'Boyle\\\'s law [P₁V₁ = P₂V₂]',
      'Charles\\\'s law [V₁/T₁ = V₂/T₂]',
      'Gay-Lussac\\\'s law [P₁/T₁ = P₂/T₂]',
      'ideal gas law [PV = nRT]',
      'Dalton\\\'s law [total pressure law]',
      'STP [0°C and 1 atm]',
      'equilibrium [dynamic balance]',
      'Le Chatelier\\\'s principle [stress response]',
      'equilibrium constant [Keq expression]',
      'reaction rate [concentration per time]',
      'activation energy [reaction energy barrier]',
      'enthalpy [ΔH measurement]',
      'exothermic reaction [releases heat]',
      'endothermic reaction [absorbs heat]',
      'entropy [ΔS value]',
      'Gibbs free energy [ΔG = ΔH − TΔS]',
      'calorimetry [q = mcΔT]',
      'specific heat [heat capacity]',
      'Hess\\\'s law [sum of steps]',
      'sublimation [dry ice example]',
      'deposition [frost formation]',
      'colligative properties [boiling point elevation]',
      'molality [concentration unit]',
      'solubility [grams per liter]',
      'saturated solution [at equilibrium]',
      'precipitation reaction [solid from solution]',
      'electrolyte [ionic compound]',
      'nonelectrolyte [molecular compound]',
      'half-life [radioactive decay rate]',
      'nuclear fission [releases energy]',
      'nuclear fusion [sun\\\'s energy source]',
      'isotope [same element variant]',
      'ion [cation or anion]'
    ]
  },
  {
    id: 'biology-easy',
    name: 'Biology - Easy',
    isStudy: true,
    words: [
      'cell (smallest unit of life) [basic life unit]',
      'nucleus (cell control center) [contains DNA]',
      'cell membrane (cell outer barrier) [controls entry and exit]',
      'cell wall (rigid plant cell layer) [plant cell support]',
      'chloroplast (photosynthesis organelle) [makes food in plants]',
      'mitochondria (cell energy maker) [powerhouse of cell]',
      'cytoplasm (jelly-like cell filling) [holds organelles]',
      'vacuole (cell storage bubble) [stores water and nutrients]',
      'ribosome (protein making structure) [builds proteins]',
      'photosynthesis (plants make glucose) [uses sunlight]',
      'carbon dioxide (gas plants absorb) [CO₂]',
      'oxygen (gas plants release) [O₂]',
      'glucose (sugar plants produce) [energy molecule]',
      'chlorophyll (green plant pigment) [absorbs sunlight]',
      'root (absorbs water underground) [plant anchor]',
      'stem (supports leaves and flowers) [plant transport]',
      'leaf (where photosynthesis occurs) [food-making organ]',
      'flower (plant reproductive structure) [makes seeds]',
      'seed (contains baby plant) [plant embryo]',
      'pollen (powdery plant fertilizer) [male plant cell]',
      'pollination (pollen reaches flower) [bee-assisted transfer]',
      'germination (seed begins growing) [sprouting process]',
      'fruit (seed-containing structure) [protects seeds]',
      'ecosystem (living and nonliving together) [community and environment]',
      'habitat (where organism lives) [natural home]',
      'food chain (energy transfer sequence) [who eats whom]',
      'producer (makes own food) [plants and algae]',
      'consumer (eats other organisms) [animals]',
      'herbivore (eats only plants) [plant eater]',
      'carnivore (eats only meat) [meat eater]',
      'omnivore (eats plants and meat) [mixed diet]',
      'decomposer (breaks down dead matter) [fungi and bacteria]',
      'predator (hunts other animals) [hunter]',
      'prey (hunted by predators) [food for predators]',
      'food web (interconnected food chains) [complex energy flow]',
      'vertebrate (animal with backbone) [fish birds mammals]',
      'invertebrate (animal without backbone) [insects worms jellyfish]',
      'mammal (warm-blooded with fur) [nurses young with milk]',
      'reptile (cold-blooded with scales) [lizards snakes turtles]',
      'amphibian (lives on land and water) [frogs salamanders]',
      'fish (aquatic with gills) [breathes underwater]',
      'bird (feathered warm-blooded animal) [lays hard eggs]',
      'insect (six-legged arthropod) [ants bees butterflies]',
      'arachnid (eight-legged arthropod) [spiders scorpions ticks]',
      'heart (pumps blood organ) [circulatory system]',
      'lungs (breathing organs) [respiratory system]',
      'brain (thinking organ) [nervous system control]',
      'stomach (digests food organ) [digestive system]',
      'skeleton (bone framework) [supports body]',
      'muscle (body movement tissue) [contracts and relaxes]',
      'skin (body outer covering) [largest organ]',
      'blood (carries oxygen through body) [red liquid]',
      'bones (hard body framework) [206 in adult body]',
      'teeth (chewing structures) [breaks down food]',
      'tongue (taste sensing organ) [five taste types]',
      'eyes (sight organs) [detect light]',
      'ears (hearing organs) [detect sound]',
      'nose (smell organ) [detects odors]',
      'life cycle (birth to death stages) [organism development]',
      'metamorphosis (dramatic body change) [caterpillar to butterfly]',
      'larva (immature insect stage) [caterpillar or grub]',
      'pupa (resting transformation stage) [chrysalis or cocoon]',
      'tadpole (immature frog stage) [has tail and gills]',
      'migration (seasonal animal movement) [birds fly south]',
      'hibernation (winter deep sleep) [bears do this]',
      'camouflage (blending with surroundings) [survival strategy]',
      'adaptation (trait for survival) [fits environment]',
      'endangered (at risk of extinction) [few left alive]',
      'extinct (no longer exists) [dinosaurs are this]',
      'species (group of similar organisms) [can reproduce together]',
      'population (same species in area) [group count]',
      'community (different species together) [living things in area]',
      'biome (large ecosystem type) [desert forest tundra]',
      'desert (hot dry biome) [little rainfall]',
      'rainforest (warm wet dense biome) [most biodiversity]',
      'ocean (saltwater biome) [largest ecosystem]',
      'tundra (cold treeless biome) [frozen ground]',
      'wetland (water-saturated land) [swamps and marshes]',
      'freshwater (not salty water) [rivers lakes ponds]',
      'bacteria (microscopic single-celled organism) [can be helpful]',
      'virus (tiny infectious particle) [causes colds and flu]',
      'fungi (decomposing organisms) [mushrooms and mold]',
      'nutrition (food for body needs) [vitamins and minerals]',
      'protein (body building nutrient) [meat beans eggs]',
      'carbohydrate (energy giving nutrient) [bread rice pasta]',
      'fat (stored energy nutrient) [butter oil nuts]',
      'vitamin (essential body nutrient) [A B C D]',
      'mineral (inorganic body nutrient) [calcium iron zinc]',
      'water cycle (evaporation and rain) [hydrological cycle]',
      'evaporation (water to vapor) [sun heats water]',
      'precipitation (water falls from clouds) [rain snow hail]',
      'condensation (vapor becomes liquid) [cloud formation]',
      'respiration (cells release energy) [uses oxygen]',
      'warm-blooded (constant body temperature) [mammals and birds]',
      'cold-blooded (variable body temperature) [reptiles and fish]',
      'nocturnal (active at night) [owls and bats]',
      'diurnal (active during day) [humans and dogs]',
      'herbivore (plant-eating animal) [rabbit deer cow]',
      'oxygen (gas animals breathe in) [needed for survival]',
      'carbon dioxide (gas animals breathe out) [waste gas]'
    ]
  },
  {
    id: 'biology-intermediate',
    name: 'Biology - Intermediate',
    isStudy: true,
    words: [
      'DNA (deoxyribonucleic acid) [genetic blueprint]',
      'RNA (ribonucleic acid) [protein synthesis messenger]',
      'gene (DNA segment for trait) [unit of heredity]',
      'chromosome (DNA package structure) [23 pairs in humans]',
      'allele (gene variant form) [dominant or recessive]',
      'dominant allele (expressed over recessive) [uppercase letter]',
      'recessive allele (masked by dominant) [lowercase letter]',
      'genotype (genetic makeup letters) [AA Aa aa]',
      'phenotype (observable trait expression) [physical appearance]',
      'heterozygous (two different alleles) [Aa carrier]',
      'homozygous (two same alleles) [AA or aa]',
      'Punnett square (cross prediction grid) [genetics tool]',
      'Mendel (father of genetics) [pea plant experiments]',
      'mutation (DNA sequence change) [source of variation]',
      'heredity (trait inheritance process) [parents to offspring]',
      'mitosis (cell division for growth) [produces identical cells]',
      'meiosis (cell division for gametes) [produces sex cells]',
      'cytokinesis (cytoplasm division) [cell splitting apart]',
      'interphase (cell growth phase) [DNA replication occurs]',
      'prophase (chromosomes condense phase) [spindle forms]',
      'metaphase (chromosomes align middle) [equatorial plate]',
      'anaphase (chromosomes separate phase) [pulled to poles]',
      'telophase (nuclear envelope reforms) [division nearly complete]',
      'gamete (reproductive sex cell) [sperm or egg]',
      'zygote (fertilized egg cell) [first cell of organism]',
      'diploid (two chromosome sets) [body cells 2n]',
      'haploid (one chromosome set) [sex cells n]',
      'crossing over (chromosome segment exchange) [genetic recombination]',
      'natural selection (survival of fittest) [Darwin\\\'s theory]',
      'evolution (species change over time) [adaptation accumulation]',
      'adaptation (evolved survival trait) [fitness advantage]',
      'speciation (new species formation) [reproductive isolation]',
      'fossil record (preserved organism evidence) [evolution proof]',
      'homologous structures (similar anatomy different function) [common ancestor]',
      'vestigial structures (reduced useless organs) [evolutionary remnants]',
      'taxonomy (organism classification science) [naming and grouping]',
      'binomial nomenclature (two-part species name) [genus and species]',
      'kingdom (highest classification level) [animal plant fungi]',
      'phylum (second classification level) [body plan group]',
      'class (third classification level) [mammalia reptilia]',
      'order (fourth classification level) [primates carnivora]',
      'family (fifth classification level) [related genera]',
      'genus (sixth classification level) [closely related species]',
      'species (most specific classification) [can interbreed]',
      'ecology (organism environment study) [interactions science]',
      'biotic factor (living ecosystem part) [plants animals fungi]',
      'abiotic factor (nonliving ecosystem part) [water sunlight soil]',
      'symbiosis (close species relationship) [living together]',
      'mutualism (both species benefit) [clownfish and anemone]',
      'parasitism (one benefits one harmed) [tick on dog]',
      'commensalism (one benefits one unaffected) [barnacle on whale]',
      'competition (organisms rival for resources) [same niche struggle]',
      'niche (organism\\\'s ecological role) [job in ecosystem]',
      'succession (ecosystem change over time) [community replacement]',
      'carrying capacity (maximum population supported) [resource limit]',
      'trophic level (feeding position level) [energy pyramid step]',
      'biomass (total living matter mass) [organic material weight]',
      'endoplasmic reticulum (membrane transport network) [smooth and rough]',
      'Golgi apparatus (protein packaging organelle) [shipping department]',
      'lysosome (digestive enzyme organelle) [cell cleanup crew]',
      'ATP (adenosine triphosphate) [energy currency]',
      'cellular respiration (glucose to ATP) [C₆H₁₂O₆ + O₂]',
      'glycolysis (glucose splitting process) [first respiration step]',
      'Krebs cycle (citric acid cycle) [second respiration step]',
      'electron transport chain (ATP production stage) [most ATP made]',
      'fermentation (anaerobic energy release) [without oxygen]',
      'enzyme (biological reaction catalyst) [protein catalyst]',
      'substrate (enzyme target molecule) [lock and key fit]',
      'active site (enzyme binding region) [substrate fits here]',
      'protein (amino acid polymer) [folded polypeptide]',
      'amino acid (protein building block) [20 types exist]',
      'lipid (fat and oil molecule) [energy storage molecule]',
      'carbohydrate (sugar and starch molecule) [quick energy source]',
      'nucleotide (DNA building block) [base sugar phosphate]',
      'codon (three-base RNA sequence) [codes for amino acid]',
      'transcription (DNA to mRNA process) [occurs in nucleus]',
      'translation (mRNA to protein process) [occurs at ribosome]',
      'replication (DNA copying process) [semiconservative method]',
      'homeostasis (internal balance maintenance) [stable internal environment]',
      'negative feedback (reverses change direction) [thermostat example]',
      'positive feedback (amplifies change direction) [blood clotting example]',
      'hormone (chemical messenger molecule) [endocrine system signal]',
      'neuron (nerve signal cell) [brain and nerve cell]',
      'synapse (nerve cell junction) [signal crossing gap]',
      'immune system (body defense network) [fights pathogens]',
      'antibody (pathogen targeting protein) [immune response molecule]',
      'antigen (immune triggering molecule) [foreign substance marker]',
      'vaccine (weakened pathogen preparation) [builds immunity]',
      'pathogen (disease causing organism) [bacteria virus parasite]',
      'antibiotic (kills bacteria medicine) [penicillin example]',
      'mitochondrial DNA (maternal genetic material) [inherited from mother]',
      'stem cell (unspecialized dividing cell) [can become any cell]',
      'cancer (uncontrolled cell division) [tumor formation]',
      'genetic engineering (DNA manipulation technology) [gene editing]',
      'GMO (genetically modified organism) [altered DNA organism]',
      'cloning (identical genetic copy) [Dolly the sheep]',
      'gel electrophoresis (DNA separation technique) [size-based sorting]',
      'PCR (DNA amplification technique) [polymerase chain reaction]',
      'plasmid (bacterial circular DNA) [gene transfer vector]',
      'biodiversity (variety of life forms) [species richness]'
    ]
  },
  {
    id: 'us-history-easy',
    name: 'US History - Easy',
    isStudy: true,
    words: [
      'George Washington (first president) [father of country]',
      'Abraham Lincoln (16th president) [freed the slaves]',
      'Thomas Jefferson (wrote famous document) [Declaration of Independence]',
      'Benjamin Franklin (inventor and diplomat) [founding father]',
      'John Adams (second president) [first vice president]',
      'James Madison (father of document) [Constitution author]',
      'Alexander Hamilton (first treasury secretary) [financial system creator]',
      'Paul Revere (midnight ride warning) [the British are coming]',
      'Betsy Ross (flag maker legend) [first American flag]',
      'Pocahontas (helped Jamestown settlers) [Native American peacemaker]',
      'Declaration of Independence (freedom document year) [1776]',
      'Constitution (supreme law document) [We the People]',
      'Bill of Rights (first ten amendments) [protects freedoms]',
      'Emancipation Proclamation (freed enslaved people) [Abraham Lincoln 1863]',
      'Gettysburg Address (famous Civil War speech) [Abraham Lincoln]',
      'Mayflower (Pilgrim ship name) [sailed to Plymouth]',
      'Plymouth Rock (Pilgrim landing spot) [Massachusetts 1620]',
      'Jamestown (first permanent settlement) [Virginia 1607]',
      'Boston Tea Party (tax protest event) [threw tea overboard]',
      'Revolutionary War (independence from Britain) [1775 to 1783]',
      'Civil War (North versus South) [1861 to 1865]',
      'World War I (first global conflict) [1914 to 1918]',
      'World War II (second global conflict) [1939 to 1945]',
      'Pearl Harbor (Japan attacked Hawaii) [December 7 1941]',
      'D-Day (Allied invasion of France) [June 6 1944]',
      'Martin Luther King Jr. (civil rights leader) [I Have a Dream]',
      'Rosa Parks (refused to move seats) [bus boycott hero]',
      'Harriet Tubman (Underground Railroad conductor) [freed enslaved people]',
      'Frederick Douglass (abolitionist speaker and writer) [former enslaved person]',
      'Susan B. Anthony (fought for women\\\'s vote) [suffrage leader]',
      'Statue of Liberty (gift from France) [symbol of freedom]',
      'Liberty Bell (cracked freedom symbol) [Philadelphia landmark]',
      'Mount Rushmore (four presidents carved) [South Dakota monument]',
      'White House (president\\\'s home) [Washington DC]',
      'Capitol Building (Congress meets here) [Washington DC landmark]',
      'Washington Monument (tall white obelisk) [DC landmark]',
      'Lincoln Memorial (seated president statue) [DC memorial]',
      'Thanksgiving (harvest celebration holiday) [Pilgrims and Natives]',
      'Independence Day (birthday of America) [July Fourth]',
      'Memorial Day (honors fallen soldiers) [last Monday in May]',
      'Veterans Day (honors all who served) [November eleventh]',
      'Presidents Day (honors US presidents) [February holiday]',
      'Columbus Day (explorer arrival day) [October holiday]',
      'Christopher Columbus (sailed to Americas) [1492 voyage]',
      'Lewis and Clark (explored the West) [Corps of Discovery]',
      'Louisiana Purchase (doubled US size) [bought from France 1803]',
      'Gold Rush (California mining rush) [1849 forty-niners]',
      'Oregon Trail (westward wagon route) [pioneer pathway]',
      'Transcontinental Railroad (coast to coast train) [completed 1869]',
      'Thomas Edison (light bulb inventor) [Menlo Park genius]',
      'Alexander Graham Bell (telephone inventor) [first phone call]',
      'Wright Brothers (first airplane flight) [Kitty Hawk 1903]',
      'Henry Ford (Model T car maker) [assembly line pioneer]',
      'Neil Armstrong (first moon walker) [one small step]',
      'Amelia Earhart (famous female pilot) [disappeared over Pacific]',
      'Teddy Roosevelt (26th president) [teddy bear namesake]',
      'Franklin Roosevelt (32nd president) [New Deal leader]',
      'John F. Kennedy (35th president) [ask not speech]',
      'Barack Obama (44th president) [first African American president]',
      'Ulysses S. Grant (Civil War general) [18th president]',
      'Robert E. Lee (Confederate general) [surrendered at Appomattox]',
      'Sacagawea (Lewis and Clark guide) [Shoshone interpreter]',
      'Sojourner Truth (abolitionist and activist) [Ain\\\'t I a Woman]',
      'First Amendment (protects free speech) [freedom of religion]',
      'Second Amendment (right to bear arms) [gun rights]',
      'Thirteenth Amendment (abolished slavery) [ratified 1865]',
      'Nineteenth Amendment (women\\\'s right to vote) [ratified 1920]',
      'Electoral College (elects the president) [voting system]',
      'Congress (Senate and House combined) [legislative branch]',
      'Supreme Court (highest court in US) [judicial branch]',
      'President (head of government) [executive branch]',
      'three branches (legislative executive judicial) [separation of powers]',
      'democracy (government by the people) [citizen voting]',
      'amendment (change to Constitution) [27 total amendments]',
      'Pledge of Allegiance (patriotic daily recitation) [I pledge allegiance]',
      'Star-Spangled Banner (national anthem name) [Francis Scott Key]',
      'American flag (stars and stripes) [red white and blue]',
      'bald eagle (national bird symbol) [American symbol]',
      'Uncle Sam (US government symbol) [I Want You poster]',
      'Alamo (famous Texas battle) [Remember the Alamo]',
      'Trail of Tears (forced Native removal) [Cherokee relocation]',
      'Underground Railroad (secret escape network) [to freedom in North]',
      'Manifest Destiny (westward expansion belief) [coast to coast]',
      'Civil Rights Act (banned discrimination law) [signed 1964]',
      'Moon Landing (Apollo 11 mission) [July 20 1969]',
      'Great Depression (worst economic crisis) [started 1929]',
      'New Deal (FDR\\\'s recovery programs) [Depression relief]',
      'Cold War (US versus Soviet tension) [nuclear arms race]',
      'Thirteen Colonies (original British settlements) [became first states]',
      'Boston Massacre (British soldiers shot colonists) [1770 incident]',
      'Minutemen (ready in sixty seconds) [colonial militia]',
      'Valley Forge (harsh winter camp) [Continental Army 1777]',
      'John Hancock (large signature signer) [Declaration first signer]',
      'Patrick Henry (give me liberty speech) [Virginia patriot]',
      'Eli Whitney (cotton gin inventor) [changed Southern farming]',
      'Samuel Morse (telegraph inventor) [Morse code creator]',
      'Dwight Eisenhower (WWII general and president) [34th president]',
      'Harry Truman (ended WWII president) [33rd president]',
      'Ellis Island (immigrant entry point) [New York Harbor]',
      'Homestead Act (free western land law) [signed 1862]'
    ]
  }
];
