export const STUDY_WORDS_2 = [
  {
    id: 'us-history-intermediate',
    name: 'US History - Intermediate',
    isStudy: true,
    words: [
      'Marbury v. Madison (Supreme Court case) [judicial review]',
      'McCulloch v. Maryland (federal vs state power) [implied powers]',
      'Dred Scott v. Sandford (slavery case) [not citizens]',
      'Plessy v. Ferguson (segregation case) [separate but equal]',
      'Brown v. Board (school segregation) [unconstitutional]',
      'Roe v. Wade (privacy rights case) [abortion legalized]',
      'Miranda v. Arizona (arrest rights) [right to silence]',
      'Gideon v. Wainwright (criminal defense) [right to attorney]',
      'Gibbons v. Ogden (trade dispute) [interstate commerce]',
      'Citizens United (campaign finance) [corporate spending]',
      '1st Amendment (Bill of Rights) [freedom of speech]',
      '2nd Amendment (Bill of Rights) [right to bear arms]',
      '4th Amendment (Bill of Rights) [search and seizure]',
      '5th Amendment (Bill of Rights) [due process]',
      '13th Amendment (Civil War era) [abolished slavery]',
      '14th Amendment (Civil War era) [equal protection]',
      '15th Amendment (Civil War era) [voting rights race]',
      '19th Amendment (women\'s suffrage) [women can vote]',
      '18th Amendment (temperance movement) [prohibition]',
      '21st Amendment (repealed prohibition) [alcohol legal again]',
      '22nd Amendment (presidential term) [two term limit]',
      '26th Amendment (Vietnam era) [voting age eighteen]',
      'Reconstruction (post-Civil War) [rebuilding the South]',
      'Freedmen\'s Bureau (Reconstruction agency) [aid former slaves]',
      'Jim Crow Laws (post-Reconstruction) [racial segregation]',
      'Sharecropping (post-Civil War labor) [tenant farming]',
      'Black Codes (Southern legislation) [restrict Black rights]',
      'Compromise of 1877 (disputed election) [ended Reconstruction]',
      'Manifest Destiny (expansion belief) [westward expansion]',
      'Monroe Doctrine (foreign policy) [no European colonies]',
      'Roosevelt Corollary (to Monroe Doctrine) [US police power]',
      'Sherman Antitrust Act (Progressive Era) [break up monopolies]',
      'Clayton Antitrust Act (trust regulation) [strengthened Sherman Act]',
      'Interstate Commerce Act (railroad regulation) [regulate railroads]',
      'Pure Food and Drug Act (consumer protection) [food safety]',
      'Muckrakers (Progressive journalists) [exposed corruption]',
      'Upton Sinclair (wrote The Jungle) [meatpacking reform]',
      'Jane Addams (social reformer) [Hull House]',
      'Susan B. Anthony (suffrage leader) [women\'s voting rights]',
      'W.E.B. Du Bois (civil rights leader) [founded NAACP]',
      'Booker T. Washington (educator) [vocational education]',
      'Treaty of Versailles (ended WWI) [punished Germany]',
      'League of Nations (post-WWI group) [international peace]',
      'Lusitania (ship sunk by Germany) [US entered WWI]',
      'Zimmermann Telegram (WWI intercepted message) [Mexico alliance plot]',
      'Pearl Harbor (Japanese attack) [US entered WWII]',
      'D-Day (WWII invasion) [Normandy landing]',
      'Manhattan Project (WWII secret program) [atomic bomb]',
      'Hiroshima (WWII bombing) [first atomic bomb used]',
      'GI Bill (post-WWII law) [veteran benefits]',
      'Marshall Plan (post-WWII aid) [rebuild Europe]',
      'Truman Doctrine (Cold War policy) [contain communism]',
      'NATO (Cold War alliance) [Western military alliance]',
      'Warsaw Pact (Cold War alliance) [Soviet military alliance]',
      'Korean War (Cold War conflict) [divided Korea]',
      'Bay of Pigs (Cuba invasion) [failed CIA operation]',
      'Cuban Missile Crisis (nuclear standoff) [Soviet missiles removed]',
      'Gulf of Tonkin (Vietnam incident) [escalated Vietnam War]',
      'Tet Offensive (Vietnam War) [turning point]',
      'War Powers Act (post-Vietnam law) [limit presidential power]',
      'Domino Theory (Cold War belief) [communism spreads]',
      'Berlin Wall (Cold War symbol) [divided Germany]',
      'Iron Curtain (Cold War term) [East-West divide]',
      'McCarthyism (Red Scare era) [anti-communist witch hunts]',
      'Brown v. Board (desegregation ruling) [end school segregation]',
      'Rosa Parks (Montgomery Bus Boycott) [refused to move]',
      'Martin Luther King Jr. (civil rights leader) [nonviolent protest]',
      'March on Washington (1963 rally) [I Have a Dream]',
      'Civil Rights Act of 1964 (landmark law) [banned discrimination]',
      'Voting Rights Act (1965 law) [protected minority voting]',
      'Malcolm X (civil rights figure) [Black nationalism]',
      'Freedom Riders (civil rights activists) [desegregate buses]',
      'Little Rock Nine (school integration) [Arkansas desegregation]',
      'Sit-ins (civil rights tactic) [nonviolent protest]',
      'New Deal (FDR\'s programs) [Great Depression relief]',
      'Social Security Act (New Deal program) [retirement benefits]',
      'Tennessee Valley Authority (New Deal agency) [rural electricity]',
      'Great Society (LBJ\'s programs) [war on poverty]',
      'Medicare (Great Society program) [elderly healthcare]',
      'Medicaid (Great Society program) [low-income healthcare]',
      'Watergate (Nixon scandal) [presidential resignation]',
      'Pentagon Papers (Vietnam secrets) [government deception]',
      'Iran-Contra Affair (Reagan scandal) [secret arms deal]',
      'Camp David Accords (peace agreement) [Egypt-Israel peace]',
      'NAFTA (trade agreement) [free trade North America]',
      'Emancipation Proclamation (Lincoln\'s order) [freed slaves]',
      'Gettysburg Address (Lincoln\'s speech) [national unity]',
      'Seneca Falls Convention (1848 meeting) [women\'s rights]',
      'Trail of Tears (Native American removal) [forced relocation]',
      'Louisiana Purchase (1803 land deal) [doubled US size]',
      'Homestead Act (1862 law) [free western land]',
      'Dawes Act (Native American policy) [tribal land division]',
      'Chinese Exclusion Act (immigration law) [banned Chinese workers]',
      'Immigration Act of 1924 (quota system) [restricted immigration]',
      'Espionage Act (WWI law) [punish war opposition]',
      'Alien and Sedition Acts (1798 laws) [limit free speech]',
      'Federalist Papers (founding documents) [support Constitution]',
      'Electoral College (election system) [indirect voting]',
      'Checks and Balances (government design) [limit power]',
      'Filibuster (Senate tactic) [delay legislation]'
    ]
  },
  {
    id: 'anatomy-easy',
    name: 'Anatomy - Easy',
    isStudy: true,
    words: [
      'Heart (pumps blood) [circulatory system]',
      'Brain (controls the body) [nervous system]',
      'Lungs (help you breathe) [respiratory system]',
      'Stomach (breaks down food) [digestive system]',
      'Liver (cleans the blood) [largest internal organ]',
      'Kidneys (filter waste) [make urine]',
      'Skin (covers your body) [largest organ]',
      'Skull (protects the brain) [head bone]',
      'Spine (supports your back) [backbone]',
      'Ribs (protect your chest) [rib cage]',
      'Femur (upper leg bone) [longest bone]',
      'Humerus (upper arm bone) [funny bone area]',
      'Patella (front of knee) [kneecap]',
      'Pelvis (supports your hips) [hip bone]',
      'Clavicle (connects arm to body) [collarbone]',
      'Scapula (back of shoulder) [shoulder blade]',
      'Sternum (front of chest) [breastbone]',
      'Tibia (lower leg bone) [shinbone]',
      'Fibula (beside the tibia) [calf bone]',
      'Radius (forearm bone) [thumb side]',
      'Biceps (front of upper arm) [bends elbow]',
      'Triceps (back of upper arm) [straightens elbow]',
      'Quadriceps (front of thigh) [extends knee]',
      'Hamstrings (back of thigh) [bends knee]',
      'Abdominals (front of belly) [core muscles]',
      'Diaphragm (below the lungs) [breathing muscle]',
      'Tongue (inside the mouth) [taste and speech]',
      'Teeth (used for chewing) [break down food]',
      'Esophagus (food tube) [throat to stomach]',
      'Small Intestine (after stomach) [absorbs nutrients]',
      'Large Intestine (end of digestion) [absorbs water]',
      'Appendix (near large intestine) [vestigial organ]',
      'Gallbladder (stores bile) [helps digest fat]',
      'Pancreas (near the stomach) [makes insulin]',
      'Trachea (air passage) [windpipe]',
      'Bronchi (branches in lungs) [airway tubes]',
      'Nostrils (openings in nose) [breathe in air]',
      'Larynx (in the throat) [voice box]',
      'Eyelid (covers the eye) [protects eye]',
      'Pupil (center of eye) [lets in light]',
      'Iris (colored part of eye) [controls pupil size]',
      'Retina (back of eye) [detects light]',
      'Cornea (front of eye) [clear covering]',
      'Eardrum (inside the ear) [vibrates with sound]',
      'Cochlea (inner ear part) [hearing organ]',
      'Red Blood Cells (in the blood) [carry oxygen]',
      'White Blood Cells (in the blood) [fight infection]',
      'Platelets (in the blood) [help clotting]',
      'Plasma (liquid in blood) [carries blood cells]',
      'Arteries (blood vessels) [carry blood away]',
      'Veins (blood vessels) [return blood to heart]',
      'Capillaries (tiny vessels) [exchange nutrients]',
      'Aorta (largest artery) [leaves the heart]',
      'Spleen (near the stomach) [filters blood]',
      'Tonsils (back of throat) [fight germs]',
      'Thyroid (in the neck) [controls metabolism]',
      'Adrenal Glands (above kidneys) [stress hormones]',
      'Pituitary Gland (base of brain) [master gland]',
      'Spinal Cord (inside spine) [carries signals]',
      'Nerves (throughout body) [send messages]',
      'Cerebrum (top of brain) [thinking and memory]',
      'Cerebellum (back of brain) [balance and movement]',
      'Brain Stem (base of brain) [basic functions]',
      'Taste Buds (on the tongue) [detect flavors]',
      'Olfactory Nerve (in the nose) [sense of smell]',
      'Hair Follicle (in the skin) [grows hair]',
      'Sweat Glands (in the skin) [cool the body]',
      'Epidermis (outer skin layer) [top layer of skin]',
      'Dermis (under epidermis) [second skin layer]',
      'Nails (on fingers and toes) [made of keratin]',
      'Ligaments (connect bones) [hold joints together]',
      'Tendons (connect muscle to bone) [help movement]',
      'Cartilage (flexible tissue) [cushions joints]',
      'Joints (where bones meet) [allow movement]',
      'Molars (back teeth) [grinding food]',
      'Canines (pointed teeth) [tearing food]',
      'Incisors (front teeth) [cutting food]',
      'Saliva (in the mouth) [starts digestion]',
      'Bladder (stores liquid waste) [holds urine]',
      'Ureters (tubes to bladder) [carry urine]',
      'Urethra (exit tube) [releases urine]',
      'Vocal Cords (in the larynx) [produce sound]',
      'Enamel (covers teeth) [hardest body substance]',
      'Marrow (inside bones) [makes blood cells]',
      'Oxygen (breathed in air) [cells need it]',
      'Carbon Dioxide (breathed out) [waste gas]',
      'Vitamins (in healthy food) [body needs them]',
      'Calcium (mineral for body) [strong bones]',
      'Iron (mineral in blood) [carries oxygen]',
      'Protein (in meat and beans) [builds muscle]',
      'Carbohydrates (in bread and rice) [give energy]',
      'Fats (in oils and butter) [store energy]',
      'Fiber (in fruits and veggies) [aids digestion]',
      'Water (essential drink) [hydrates the body]',
      'Exercise (physical activity) [keeps body healthy]',
      'Sleep (rest at night) [body repairs itself]',
      'Pulse (felt at wrist) [heartbeat rate]',
      'Temperature (body heat level) [98.6 degrees F]',
      'Reflexes (automatic response) [involuntary movement]',
      'Posture (how you stand) [body alignment]'
    ]
  },
  {
    id: 'anatomy-intermediate',
    name: 'Anatomy - Intermediate',
    isStudy: true,
    words: [
      'Osteocyte (bone cell type) [mature bone cell]',
      'Osteoblast (bone cell type) [builds new bone]',
      'Osteoclast (bone cell type) [breaks down bone]',
      'Periosteum (bone covering) [outer bone membrane]',
      'Epiphysis (bone region) [end of long bone]',
      'Diaphysis (bone region) [shaft of long bone]',
      'Haversian Canal (compact bone) [blood vessel channel]',
      'Ossification (bone formation) [cartilage becomes bone]',
      'Synovial Joint (movable joint) [fluid-filled joint]',
      'Ligament (connective tissue) [bone to bone]',
      'Tendon (connective tissue) [muscle to bone]',
      'Bursa (joint structure) [reduces friction]',
      'Meniscus (knee cartilage) [shock absorber]',
      'Intervertebral Disc (spine cushion) [between vertebrae]',
      'Sarcomere (muscle unit) [contractile unit]',
      'Myofibril (muscle fiber part) [contains sarcomeres]',
      'Actin (muscle protein) [thin filament]',
      'Myosin (muscle protein) [thick filament]',
      'Neuromuscular Junction (nerve-muscle meeting) [signal transmission]',
      'Skeletal Muscle (voluntary muscle) [moves skeleton]',
      'Smooth Muscle (involuntary muscle) [lines organs]',
      'Cardiac Muscle (heart muscle) [involuntary striated]',
      'Fascia (connective tissue) [surrounds muscles]',
      'Muscle Contraction (sliding filament) [shortens muscle]',
      'Sinoatrial Node (heart pacemaker) [sets heart rate]',
      'Atrioventricular Node (heart conduction) [delays signal]',
      'Right Atrium (heart chamber) [receives deoxygenated blood]',
      'Left Ventricle (heart chamber) [pumps to body]',
      'Pulmonary Artery (heart vessel) [carries blood to lungs]',
      'Pulmonary Vein (heart vessel) [returns oxygenated blood]',
      'Aortic Valve (heart valve) [prevents backflow]',
      'Systole (cardiac cycle) [heart contraction]',
      'Diastole (cardiac cycle) [heart relaxation]',
      'Blood Pressure (cardiovascular measure) [systolic over diastolic]',
      'Hemoglobin (red blood cell protein) [carries oxygen]',
      'Erythrocyte (blood cell type) [red blood cell]',
      'Leukocyte (blood cell type) [white blood cell]',
      'Thrombocyte (blood component) [platelet]',
      'Alveoli (lung structures) [gas exchange]',
      'Bronchioles (lung airways) [small air passages]',
      'Pleura (lung membrane) [surrounds lungs]',
      'Surfactant (lung substance) [reduces surface tension]',
      'Diaphragm (respiratory muscle) [primary breathing muscle]',
      'Tidal Volume (breathing measure) [normal breath volume]',
      'Vital Capacity (lung measure) [maximum air exhaled]',
      'Cerebral Cortex (brain surface) [higher thinking]',
      'Frontal Lobe (brain region) [decision making]',
      'Temporal Lobe (brain region) [hearing and memory]',
      'Occipital Lobe (brain region) [visual processing]',
      'Parietal Lobe (brain region) [sensory processing]',
      'Hypothalamus (brain structure) [homeostasis control]',
      'Thalamus (brain structure) [sensory relay station]',
      'Medulla Oblongata (brainstem part) [vital functions]',
      'Myelin Sheath (nerve covering) [speeds nerve signals]',
      'Synapse (nerve gap) [neurotransmitter release]',
      'Axon (neuron part) [carries signals away]',
      'Dendrite (neuron part) [receives signals]',
      'Neurotransmitter (chemical messenger) [crosses synapse]',
      'Sympathetic Nervous System (autonomic division) [fight or flight]',
      'Parasympathetic Nervous System (autonomic division) [rest and digest]',
      'Thyroid Gland (endocrine gland) [metabolism regulation]',
      'Adrenal Cortex (adrenal region) [cortisol production]',
      'Adrenal Medulla (adrenal region) [epinephrine production]',
      'Insulin (pancreatic hormone) [lowers blood sugar]',
      'Glucagon (pancreatic hormone) [raises blood sugar]',
      'Estrogen (sex hormone) [female development]',
      'Testosterone (sex hormone) [male development]',
      'Growth Hormone (pituitary hormone) [stimulates growth]',
      'Thymus (lymphatic organ) [T cell maturation]',
      'Lymph Nodes (lymphatic structures) [filter lymph fluid]',
      'Spleen (lymphatic organ) [filters blood]',
      'Lymphocyte (immune cell) [adaptive immunity]',
      'Antibody (immune protein) [targets pathogens]',
      'Antigen (foreign substance) [triggers immune response]',
      'Nephron (kidney unit) [filters blood]',
      'Glomerulus (kidney structure) [filtration unit]',
      'Bowman\'s Capsule (kidney structure) [surrounds glomerulus]',
      'Loop of Henle (nephron part) [concentrates urine]',
      'Collecting Duct (kidney tube) [final urine processing]',
      'Ovary (female organ) [produces eggs]',
      'Testis (male organ) [produces sperm]',
      'Uterus (female organ) [fetal development]',
      'Fallopian Tube (female anatomy) [egg transport]',
      'Zygote (fertilized egg) [first cell]',
      'Epithelial Tissue (body tissue) [covers surfaces]',
      'Connective Tissue (body tissue) [supports structures]',
      'Nervous Tissue (body tissue) [transmits impulses]',
      'Muscle Tissue (body tissue) [produces movement]',
      'Homeostasis (body regulation) [internal balance]',
      'Mitosis (cell division) [identical daughter cells]',
      'Meiosis (cell division) [gamete production]',
      'ATP (energy molecule) [cellular energy currency]',
      'Cellular Respiration (energy process) [glucose to ATP]',
      'Osmosis (water movement) [across membrane]',
      'Diffusion (particle movement) [high to low concentration]',
      'pH Balance (body chemistry) [acid-base balance]',
      'Enzymes (biological catalysts) [speed up reactions]',
      'Metabolism (body processes) [chemical reactions in body]',
      'Anatomical Position (body reference) [standard body position]',
      'Anterior and Posterior (directional terms) [front and back]'
    ]
  },
  {
    id: 'world-history-easy',
    name: 'World History - Easy',
    isStudy: true,
    words: [
      'Pharaoh (Egyptian ruler) [king of Egypt]',
      'Pyramids (Egyptian structures) [tombs for pharaohs]',
      'Sphinx (Egyptian monument) [lion with human head]',
      'Hieroglyphics (Egyptian writing) [picture symbols]',
      'Mummies (preserved bodies) [ancient Egyptian burial]',
      'Cleopatra (Egyptian queen) [last pharaoh]',
      'King Tut (boy pharaoh) [Tutankhamun]',
      'Nile River (Egyptian river) [longest river in Africa]',
      'Zeus (Greek mythology) [king of the gods]',
      'Athena (Greek goddess) [goddess of wisdom]',
      'Poseidon (Greek god) [god of the sea]',
      'Hercules (Greek hero) [son of Zeus]',
      'Olympics (ancient Greece) [athletic competition]',
      'Parthenon (Greek building) [temple to Athena]',
      'Democracy (Greek invention) [rule by the people]',
      'Socrates (Greek thinker) [famous philosopher]',
      'Alexander the Great (Greek king) [conquered vast empire]',
      'Trojan Horse (Greek legend) [hidden soldiers inside]',
      'Colosseum (Roman arena) [gladiator fights]',
      'Julius Caesar (Roman leader) [assassinated ruler]',
      'Roman Empire (ancient civilization) [ruled Mediterranean]',
      'Gladiators (Roman fighters) [arena warriors]',
      'Aqueducts (Roman invention) [carried water]',
      'Roman Roads (ancient highways) [connected the empire]',
      'Augustus (first emperor) [Roman Empire founder]',
      'Pompeii (Roman city) [buried by volcano]',
      'Great Wall (Chinese structure) [defense wall]',
      'Silk Road (ancient trade route) [connected East and West]',
      'Confucius (Chinese philosopher) [teachings on morality]',
      'Terracotta Army (Chinese tomb) [clay soldiers]',
      'Samurai (Japanese warriors) [feudal fighters]',
      'Vikings (Norse explorers) [Scandinavian raiders]',
      'Marco Polo (Italian explorer) [traveled to China]',
      'Christopher Columbus (explorer) [reached the Americas]',
      'Ferdinand Magellan (explorer) [first circumnavigation]',
      'Vasco da Gama (Portuguese explorer) [sailed to India]',
      'Leif Erikson (Norse explorer) [reached North America]',
      'Compass (navigation tool) [points north]',
      'Printing Press (Gutenberg invention) [mass-produced books]',
      'Wheel (ancient invention) [transportation tool]',
      'Paper (Chinese invention) [writing material]',
      'Gunpowder (Chinese invention) [explosive powder]',
      'Telescope (Galileo\'s tool) [see distant objects]',
      'Steam Engine (industrial invention) [powered by steam]',
      'Electricity (modern discovery) [powers devices]',
      'Telephone (Bell\'s invention) [voice communication]',
      'Light Bulb (Edison\'s invention) [artificial light]',
      'Airplane (Wright Brothers) [powered flight]',
      'Gandhi (Indian leader) [nonviolent independence]',
      'Nelson Mandela (South African leader) [ended apartheid]',
      'Queen Victoria (British monarch) [Victorian Era]',
      'Napoleon (French emperor) [conquered Europe]',
      'Winston Churchill (British PM) [WWII leader]',
      'Genghis Khan (Mongol leader) [largest land empire]',
      'Africa (continent) [second largest continent]',
      'Asia (continent) [largest continent]',
      'Europe (continent) [western part of Eurasia]',
      'South America (continent) [Amazon Rainforest]',
      'Antarctica (continent) [coldest continent]',
      'Australia (continent) [smallest continent]',
      'North America (continent) [third largest continent]',
      'Christianity (world religion) [follows Jesus Christ]',
      'Islam (world religion) [follows Muhammad]',
      'Buddhism (world religion) [founded by Buddha]',
      'Hinduism (world religion) [oldest major religion]',
      'Judaism (world religion) [Torah is holy book]',
      'Great Pyramid of Giza (ancient wonder) [oldest wonder]',
      'Hanging Gardens (ancient wonder) [Babylon gardens]',
      'Lighthouse of Alexandria (ancient wonder) [guided ships]',
      'Colossus of Rhodes (ancient wonder) [giant statue]',
      'Eiffel Tower (Paris landmark) [iron tower]',
      'Taj Mahal (Indian landmark) [marble mausoleum]',
      'Big Ben (London landmark) [clock tower]',
      'Great Barrier Reef (Australian landmark) [coral reef]',
      'Machu Picchu (Inca ruins) [mountain citadel]',
      'Stonehenge (English monument) [stone circle]',
      'Chichen Itza (Mayan ruins) [pyramid temple]',
      'Easter Island (Pacific island) [stone head statues]',
      'Chinese New Year (Asian holiday) [lunar new year]',
      'Diwali (Hindu festival) [festival of lights]',
      'Day of the Dead (Mexican tradition) [honor deceased]',
      'Carnival (Brazilian celebration) [pre-Lent festival]',
      'Kimono (Japanese clothing) [traditional robe]',
      'Sari (Indian clothing) [draped garment]',
      'Boomerang (Australian tool) [returning throw stick]',
      'Totem Pole (Native American art) [carved wooden pole]',
      'Mesopotamia (ancient region) [cradle of civilization]',
      'Hammurabi (Babylonian king) [first written laws]',
      'Rosetta Stone (Egyptian artifact) [decoded hieroglyphics]',
      'Iron Age (historical period) [iron tools era]',
      'Bronze Age (historical period) [bronze tools era]',
      'Stone Age (earliest period) [stone tools era]',
      'Feudalism (medieval system) [lords and serfs]',
      'Castles (medieval structures) [fortified homes]',
      'Knights (medieval warriors) [armored fighters]',
      'Crusades (medieval wars) [religious wars]',
      'Black Death (medieval plague) [killed millions]',
      'Renaissance (cultural rebirth) [art and learning]',
      'Leonardo da Vinci (Renaissance artist) [Mona Lisa painter]',
      'Michelangelo (Renaissance artist) [Sistine Chapel]'
    ]
  },
  {
    id: 'world-history-intermediate',
    name: 'World History - Intermediate',
    isStudy: true,
    words: [
      'Renaissance (14th-17th century) [cultural rebirth]',
      'Humanism (Renaissance philosophy) [focus on humans]',
      'Niccolo Machiavelli (political thinker) [The Prince]',
      'Medici Family (Florence rulers) [Renaissance patrons]',
      'Gutenberg Bible (first printed book) [movable type]',
      'Protestant Reformation (religious movement) [split from Catholic]',
      'Martin Luther (German reformer) [95 Theses]',
      'John Calvin (religious reformer) [predestination]',
      'Henry VIII (English king) [broke with Rome]',
      'Counter-Reformation (Catholic response) [Council of Trent]',
      'Jesuits (Catholic order) [Society of Jesus]',
      'Inquisition (Church tribunal) [punish heresy]',
      'Treaty of Tordesillas (1494 agreement) [divided new world]',
      'Hernan Cortes (Spanish conquistador) [conquered Aztecs]',
      'Francisco Pizarro (Spanish conquistador) [conquered Incas]',
      'Columbian Exchange (global transfer) [crops and diseases]',
      'Triangular Trade (Atlantic commerce) [slaves goods raw materials]',
      'Middle Passage (slave trade route) [Africa to Americas]',
      'Mercantilism (economic system) [export more than import]',
      'East India Company (trading company) [colonial trade monopoly]',
      'Scramble for Africa (1880s-1900s) [European colonization]',
      'Berlin Conference (1884 meeting) [divided Africa]',
      'Opium Wars (China vs Britain) [forced open trade]',
      'Meiji Restoration (Japanese reform) [modernized Japan]',
      'French Revolution (1789 uprising) [overthrew monarchy]',
      'Bastille (French prison) [stormed by revolutionaries]',
      'Reign of Terror (French Revolution) [mass executions]',
      'Robespierre (French revolutionary) [led the Terror]',
      'Declaration of Rights of Man (French document) [natural rights]',
      'Napoleon Bonaparte (French emperor) [conquered Europe]',
      'Napoleonic Code (legal system) [civil law reform]',
      'Congress of Vienna (1815 meeting) [restored balance of power]',
      'Haitian Revolution (slave revolt) [first Black republic]',
      'Simon Bolivar (South American liberator) [freed colonies]',
      'Industrial Revolution (economic transformation) [factory production]',
      'Adam Smith (economist) [Wealth of Nations]',
      'Karl Marx (political theorist) [Communist Manifesto]',
      'Capitalism (economic system) [private ownership]',
      'Socialism (economic system) [shared ownership]',
      'Communism (political ideology) [classless society]',
      'Luddites (British protesters) [opposed machinery]',
      'Child Labor (industrial problem) [factory children]',
      'Labor Unions (worker organizations) [collective bargaining]',
      'Suffragette Movement (women\'s rights) [right to vote]',
      'Archduke Franz Ferdinand (assassination victim) [sparked WWI]',
      'Triple Alliance (WWI alliance) [Germany Austria Italy]',
      'Triple Entente (WWI alliance) [Britain France Russia]',
      'Trench Warfare (WWI combat) [static front lines]',
      'Mustard Gas (WWI weapon) [chemical warfare]',
      'Armistice (end of WWI) [November 11 1918]',
      'Treaty of Versailles (post-WWI treaty) [punished Germany]',
      'League of Nations (post-WWI organization) [collective security]',
      'Weimar Republic (German government) [post-WWI Germany]',
      'Adolf Hitler (Nazi leader) [started WWII]',
      'Fascism (political ideology) [authoritarian nationalism]',
      'Appeasement (pre-WWII policy) [concessions to Hitler]',
      'Blitzkrieg (German tactic) [lightning war]',
      'Holocaust (Nazi genocide) [six million Jews killed]',
      'D-Day Invasion (June 6 1944) [Normandy landings]',
      'Atomic Bombings (end of WWII) [Hiroshima and Nagasaki]',
      'United Nations (post-WWII organization) [international cooperation]',
      'Universal Declaration (1948 document) [human rights]',
      'Nuremberg Trials (post-WWII courts) [prosecuted war crimes]',
      'Iron Curtain (Cold War division) [East-West divide]',
      'Berlin Wall (Cold War symbol) [divided Berlin]',
      'Cuban Missile Crisis (1962 standoff) [nuclear threat]',
      'Space Race (Cold War competition) [US vs Soviet space]',
      'Proxy Wars (Cold War conflicts) [indirect superpower wars]',
      'Korean War (Cold War conflict) [divided Korea]',
      'Vietnam War (Cold War conflict) [US vs North Vietnam]',
      'Detente (Cold War relaxation) [reduced tensions]',
      'Glasnost (Soviet reform) [openness policy]',
      'Perestroika (Soviet reform) [economic restructuring]',
      'Fall of USSR (1991 event) [end of Soviet Union]',
      'Indian Independence (1947 event) [British withdrawal]',
      'Partition of India (1947 division) [India and Pakistan]',
      'Apartheid (South African policy) [racial segregation]',
      'Rwandan Genocide (1994 tragedy) [ethnic mass killing]',
      'Tiananmen Square (1989 protest) [Chinese democracy movement]',
      'Arab Spring (2010s uprisings) [Middle East protests]',
      'European Union (political union) [European integration]',
      'Bretton Woods (1944 conference) [global financial system]',
      'World Trade Organization (trade body) [regulates global trade]',
      'Geneva Conventions (humanitarian laws) [rules of war]',
      'Marshall Plan (post-WWII aid) [rebuilt Europe]',
      'NATO (military alliance) [Western defense pact]',
      'Warsaw Pact (military alliance) [Soviet defense bloc]',
      'Camp David Accords (1978 agreement) [Egypt-Israel peace]',
      'Oslo Accords (1993 agreement) [Israeli-Palestinian peace]',
      'Good Friday Agreement (1998 deal) [Northern Ireland peace]',
      'Balfour Declaration (1917 statement) [Jewish homeland]',
      'Sykes-Picot Agreement (1916 deal) [divided Middle East]',
      'Treaty of Nanking (1842 treaty) [ended First Opium War]',
      'Magna Carta (1215 document) [limited king\'s power]',
      'English Bill of Rights (1689 law) [parliamentary power]',
      'Enlightenment (intellectual movement) [reason over tradition]',
      'John Locke (Enlightenment thinker) [natural rights]',
      'Voltaire (French philosopher) [freedom of speech]',
      'Jean-Jacques Rousseau (philosopher) [social contract]',
      'Decolonization (post-WWII process) [colonies gain freedom]'
    ]
  }
];
